//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class DefaultSettings : Neo.ApplicationFramework.Tools.Recipe.Recipe
	{
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Default_Display_Unit_Low;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Default_Display_Unit_Mid;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Default_Meter_Low;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Default_Meter_Mid;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Firmware_number;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Serial_number;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Display_Press_Unit;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Default_Press_Meter_Unit;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Low_Min_FlowRate;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Low_Max_FlowRate;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Mid_Min_FlowRate;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Mid_Max_FlowRate;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Inlet_Press_Max;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Test_Press_Max;
		
		public DefaultSettings()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Default_Display_Unit_Low
		{
			get
			{
				return this.m_Default_Display_Unit_Low;
			}
			set
			{
				this.m_Default_Display_Unit_Low = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Default_Display_Unit_Mid
		{
			get
			{
				return this.m_Default_Display_Unit_Mid;
			}
			set
			{
				this.m_Default_Display_Unit_Mid = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Default_Meter_Low
		{
			get
			{
				return this.m_Default_Meter_Low;
			}
			set
			{
				this.m_Default_Meter_Low = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Default_Meter_Mid
		{
			get
			{
				return this.m_Default_Meter_Mid;
			}
			set
			{
				this.m_Default_Meter_Mid = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Firmware_number
		{
			get
			{
				return this.m_Firmware_number;
			}
			set
			{
				this.m_Firmware_number = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Serial_number
		{
			get
			{
				return this.m_Serial_number;
			}
			set
			{
				this.m_Serial_number = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Display_Press_Unit
		{
			get
			{
				return this.m_Display_Press_Unit;
			}
			set
			{
				this.m_Display_Press_Unit = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Default_Press_Meter_Unit
		{
			get
			{
				return this.m_Default_Press_Meter_Unit;
			}
			set
			{
				this.m_Default_Press_Meter_Unit = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Low_Min_FlowRate
		{
			get
			{
				return this.m_Low_Min_FlowRate;
			}
			set
			{
				this.m_Low_Min_FlowRate = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Low_Max_FlowRate
		{
			get
			{
				return this.m_Low_Max_FlowRate;
			}
			set
			{
				this.m_Low_Max_FlowRate = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Mid_Min_FlowRate
		{
			get
			{
				return this.m_Mid_Min_FlowRate;
			}
			set
			{
				this.m_Mid_Min_FlowRate = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Mid_Max_FlowRate
		{
			get
			{
				return this.m_Mid_Max_FlowRate;
			}
			set
			{
				this.m_Mid_Max_FlowRate = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Inlet_Press_Max
		{
			get
			{
				return this.m_Inlet_Press_Max;
			}
			set
			{
				this.m_Inlet_Press_Max = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Test_Press_Max
		{
			get
			{
				return this.m_Test_Press_Max;
			}
			set
			{
				this.m_Test_Press_Max = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public override void ConnectDataBindings()
		{
			base.ConnectDataBindings();
		}
		
		private void InitializeObjectCreations()
		{
			this.Default_Display_Unit_Low = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Default_Display_Unit_Mid = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Default_Meter_Low = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Default_Meter_Mid = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Firmware_number = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Serial_number = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Display_Press_Unit = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Default_Press_Meter_Unit = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Low_Min_FlowRate = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Low_Max_FlowRate = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Mid_Min_FlowRate = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Mid_Max_FlowRate = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Inlet_Press_Max = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Test_Press_Max = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.DataVersion = ((long)(347));
			this.FieldNames.Add("Default_Setting");
			this.FieldNames.Add("Notes");
			this.Guid = new System.Guid("6a08bffd-f668-4e5a-a9e8-583880274270");
			this.Default_Display_Unit_Low.ColumnName = "Default_Display_Unit_Low";
			this.Default_Display_Unit_Low.DataConnection = "Tags.flow_unit_low";
			this.Default_Display_Unit_Low.Name = "Default_Display_Unit_Low";
			this.Default_Display_Unit_Low.VisualSortOrder = 99;
			this.Default_Display_Unit_Mid.ColumnName = "Default_Display_Unit_Mid";
			this.Default_Display_Unit_Mid.DataConnection = "Tags.flow_unit_mid";
			this.Default_Display_Unit_Mid.Name = "Default_Display_Unit_Mid";
			this.Default_Display_Unit_Mid.VisualSortOrder = 100;
			this.Default_Meter_Low.ColumnName = "Default_Meter_Low";
			this.Default_Meter_Low.DataConnection = "Tags.meter_unit_low";
			this.Default_Meter_Low.Name = "Default_Meter_Low";
			this.Default_Meter_Low.VisualSortOrder = 101;
			this.Default_Meter_Mid.ColumnName = "Default_Meter_Mid";
			this.Default_Meter_Mid.DataConnection = "Tags.meter_unit_mid";
			this.Default_Meter_Mid.Name = "Default_Meter_Mid";
			this.Default_Meter_Mid.VisualSortOrder = 102;
			this.Firmware_number.ColumnName = "Firmware_number";
			this.Firmware_number.DataConnection = "Tags.firmware";
			this.Firmware_number.Name = "Firmware_number";
			this.Firmware_number.VisualSortOrder = 103;
			this.Serial_number.ColumnName = "Serial_number";
			this.Serial_number.DataConnection = "Tags.serial";
			this.Serial_number.Name = "Serial_number";
			this.Serial_number.VisualSortOrder = 104;
			this.Display_Press_Unit.ColumnName = "Display_Press_Unit";
			this.Display_Press_Unit.DataConnection = "Tags.PressUnit";
			this.Display_Press_Unit.Name = "Display_Press_Unit";
			this.Display_Press_Unit.VisualSortOrder = 105;
			this.Default_Press_Meter_Unit.ColumnName = "Default_Press_Meter_Unit";
			this.Default_Press_Meter_Unit.DataConnection = "Tags.press_meter_unit";
			this.Default_Press_Meter_Unit.Name = "Default_Press_Meter_Unit";
			this.Default_Press_Meter_Unit.VisualSortOrder = 106;
			this.Low_Min_FlowRate.ColumnName = "Low_Min_FlowRate";
			this.Low_Min_FlowRate.DataConnection = "Tags.LowRangeMin";
			this.Low_Min_FlowRate.Name = "Low_Min_FlowRate";
			this.Low_Min_FlowRate.VisualSortOrder = 107;
			this.Low_Max_FlowRate.ColumnName = "Low_Max_FlowRate";
			this.Low_Max_FlowRate.DataConnection = "Tags.LowRangeMax";
			this.Low_Max_FlowRate.Name = "Low_Max_FlowRate";
			this.Low_Max_FlowRate.VisualSortOrder = 108;
			this.Mid_Min_FlowRate.ColumnName = "Mid_Min_FlowRate";
			this.Mid_Min_FlowRate.DataConnection = "Tags.MidRangeMin";
			this.Mid_Min_FlowRate.Name = "Mid_Min_FlowRate";
			this.Mid_Min_FlowRate.VisualSortOrder = 109;
			this.Mid_Max_FlowRate.ColumnName = "Mid_Max_FlowRate";
			this.Mid_Max_FlowRate.DataConnection = "Tags.MidRangeMax";
			this.Mid_Max_FlowRate.Name = "Mid_Max_FlowRate";
			this.Mid_Max_FlowRate.VisualSortOrder = 110;
			this.Inlet_Press_Max.ColumnName = "Inlet_Press_Max";
			this.Inlet_Press_Max.DataConnection = "Tags.Inlet_Press_Max";
			this.Inlet_Press_Max.Name = "Inlet_Press_Max";
			this.Inlet_Press_Max.VisualSortOrder = 111;
			this.Test_Press_Max.ColumnName = "Test_Press_Max";
			this.Test_Press_Max.DataConnection = "Tags.Test_Press_Max";
			this.Test_Press_Max.Name = "Test_Press_Max";
			this.Test_Press_Max.VisualSortOrder = 112;
			this.RecipeItems.Add(this.Default_Display_Unit_Low);
			this.RecipeItems.Add(this.Default_Display_Unit_Mid);
			this.RecipeItems.Add(this.Default_Meter_Low);
			this.RecipeItems.Add(this.Default_Meter_Mid);
			this.RecipeItems.Add(this.Firmware_number);
			this.RecipeItems.Add(this.Serial_number);
			this.RecipeItems.Add(this.Display_Press_Unit);
			this.RecipeItems.Add(this.Default_Press_Meter_Unit);
			this.RecipeItems.Add(this.Low_Min_FlowRate);
			this.RecipeItems.Add(this.Low_Max_FlowRate);
			this.RecipeItems.Add(this.Mid_Min_FlowRate);
			this.RecipeItems.Add(this.Mid_Max_FlowRate);
			this.RecipeItems.Add(this.Inlet_Press_Max);
			this.RecipeItems.Add(this.Test_Press_Max);
			this.SchemaVersion = ((long)(591));
			this.TableName = "DefaultSettings";
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(DefaultSettings));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
