//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class DiagPreCheck : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblMsg;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnContinue;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnBack;
        
        private Neo.ApplicationFramework.Controls.Controls.LinearMeterCF m_prgDiag;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblPrg;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_prgGroup;
        
        private bool m_Initialized_DiagPreCheck;
        
        public DiagPreCheck() {
            this.InitializeComponent();
            this.btnContinue.Click += new System.EventHandler(this.btnContinue_Click);
            this.btnBack.Click += new System.EventHandler(this.btnBack_Click);
            this.Adapter.Closed += new System.EventHandler(this.DiagPreCheck_Closed);
            this.Adapter.Opened += new System.EventHandler(this.DiagPreCheck_Opened);
            this.Opened += new System.EventHandler(this.DiagPreCheck_Action_Opened);
            this.m_btnContinue.Click += new System.EventHandler(this.m_btnContinue_Action_Click);
            this.m_btnBack.Click += new System.EventHandler(this.m_btnBack_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblMsg {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblMsg);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnContinue {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnContinue);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnBack {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnBack);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter prgGroup {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_prgGroup);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LinearMeterBaseCFAdapter prgDiag {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LinearMeterBaseCFAdapter>(this.m_prgDiag);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblPrg {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblPrg);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_lblMsg = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_btnContinue = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnBack = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_prgDiag = new Neo.ApplicationFramework.Controls.Controls.LinearMeterCF();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_lblPrg = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_prgGroup = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsg)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnContinue)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnBack)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prgDiag)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblPrg)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prgGroup)).BeginInit();
            this.SuspendLayout();
            // 
            // DiagPreCheck
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227))))), System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_lblMsg
            // 
            this.m_lblMsg.AutoSize = false;
            this.m_lblMsg.BlinkDynamicsValue = false;
            this.m_lblMsg.EnabledDynamicsValue = true;
            this.m_lblMsg.FontSizePixels = 16;
            this.m_lblMsg.Height = 123;
            this.m_lblMsg.Left = 22;
            this.m_lblMsg.MultiLine = true;
            this.m_lblMsg.Name = "m_lblMsg";
            this.m_lblMsg.ScreenOwnerName = "DiagPreCheck";
            this.m_lblMsg.Top = 18;
            this.m_lblMsg.VisibleDynamicsValue = true;
            this.m_lblMsg.Width = 301;
            this.m_lblMsg.WordWrap = true;
            // 
            // m_btnContinue
            // 
            this.m_btnContinue.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnContinue.BlinkDynamicsValue = false;
            this.m_btnContinue.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnContinue.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnContinue.EnabledDynamicsValue = true;
            this.m_btnContinue.FontSizePixels = 16;
            this.m_btnContinue.ForceTransparency = true;
            this.m_btnContinue.Height = 37;
            this.m_btnContinue.IndicatorMargin = null;
            this.m_btnContinue.Left = 46;
            this.m_btnContinue.Name = "m_btnContinue";
            this.m_btnContinue.RequiresTransparency = true;
            this.m_btnContinue.ScreenOwnerName = "DiagPreCheck";
            this.m_btnContinue.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_btnContinue.TextHeight = 19;
            this.m_btnContinue.TextValue = 0D;
            this.m_btnContinue.TextWidth = 79;
            this.m_btnContinue.Top = 139;
            this.m_btnContinue.Value = 0D;
            this.m_btnContinue.Visible = false;
            this.m_btnContinue.VisualPropertiesHashCode = -586826984;
            this.m_btnContinue.Width = 89;
            // 
            // m_btnBack
            // 
            this.m_btnBack.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnBack.BlinkDynamicsValue = false;
            this.m_btnBack.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnBack.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnBack.EnabledDynamicsValue = true;
            this.m_btnBack.FontSizePixels = 16;
            this.m_btnBack.ForceTransparency = true;
            this.m_btnBack.Height = 37;
            this.m_btnBack.IndicatorMargin = null;
            this.m_btnBack.Left = 205;
            this.m_btnBack.Name = "m_btnBack";
            this.m_btnBack.RequiresTransparency = true;
            this.m_btnBack.ScreenOwnerName = "DiagPreCheck";
            this.m_btnBack.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_btnBack.TextHeight = 19;
            this.m_btnBack.TextValue = 0D;
            this.m_btnBack.TextWidth = 79;
            this.m_btnBack.Top = 139;
            this.m_btnBack.Value = 0D;
            this.m_btnBack.Visible = false;
            this.m_btnBack.VisualPropertiesHashCode = -586826984;
            this.m_btnBack.Width = 89;
            // 
            // m_prgDiag
            // 
            this.m_prgDiag.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_prgDiag.BlinkDynamicsValue = false;
            this.m_prgDiag.EnabledDynamicsValue = true;
            this.m_prgDiag.FontSizePixels = 7;
            this.m_prgDiag.ForceTransparency = false;
            this.m_prgDiag.Foreground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_prgDiag.Height = 97;
            this.m_prgDiag.IndicatorColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0))))), System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(255)))), ((int)(((byte)(26))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            this.m_prgDiag.IndicatorMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(28.910000000000007D, 22.450000000000003D, 28.909999999999968D, 25D);
            this.m_prgDiag.InvalidateAtValueChanged = true;
            this.m_prgDiag.Left = 0;
            this.m_prgDiag.MajorScaleMarginFirst = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(double.NaN, double.NaN, double.NaN, double.NaN);
            this.m_prgDiag.MajorScaleMarginSecond = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(27.910000000000007D, 75D, 27.909999999999968D, 12D);
            this.m_prgDiag.MajorTickCount = 11;
            this.m_prgDiag.Maximum = 100D;
            this.m_prgDiag.Minimum = 0D;
            this.m_prgDiag.MinorScaleMarginFirst = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(double.NaN, double.NaN, double.NaN, double.NaN);
            this.m_prgDiag.MinorScaleMarginSecond = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(27.910000000000007D, 78.25D, 27.909999999999968D, 16.25D);
            this.m_prgDiag.MinorTickCount = 1;
            this.m_prgDiag.Name = "m_prgDiag";
            this.m_prgDiag.Orientation = Neo.ApplicationFramework.Controls.Controls.OrientationCF.Horizontal;
            this.m_prgDiag.RequiresTransparency = true;
            this.m_prgDiag.ScaleColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_prgDiag.ScaleVisible = false;
            this.m_prgDiag.ScreenOwnerName = "DiagPreCheck";
            this.m_prgDiag.TextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(22.180000000000007D, 12D, 22.180000000000007D, 76.55D);
            this.m_prgDiag.Top = 0;
            this.m_prgDiag.VisibleDynamicsValue = true;
            this.m_prgDiag.Width = 353;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle.Height = 53;
            this.m_Rectangle.Left = 27;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "DiagPreCheck";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Top = 21;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 299;
            // 
            // m_lblPrg
            // 
            this.m_lblPrg.AutoSize = false;
            this.m_lblPrg.BlinkDynamicsValue = false;
            this.m_lblPrg.EnabledDynamicsValue = true;
            this.m_lblPrg.FontSizePixels = 16;
            this.m_lblPrg.Height = 53;
            this.m_lblPrg.Left = 23;
            this.m_lblPrg.MultiLine = true;
            this.m_lblPrg.Name = "m_lblPrg";
            this.m_lblPrg.ScreenOwnerName = "DiagPreCheck";
            this.m_lblPrg.TextHorizontalAlignment = "Center";
            this.m_lblPrg.TextVerticalAlignment = "Center";
            this.m_lblPrg.Top = 21;
            this.m_lblPrg.VisibleDynamicsValue = true;
            this.m_lblPrg.Width = 301;
            this.m_lblPrg.WordWrap = true;
            // 
            // m_prgGroup
            // 
            this.m_prgGroup.BlinkDynamicsValue = false;
            this.m_prgGroup.Components.Add(this.m_prgDiag);
            this.m_prgGroup.Components.Add(this.m_Rectangle);
            this.m_prgGroup.Components.Add(this.m_lblPrg);
            this.m_prgGroup.EnabledDynamicsValue = true;
            this.m_prgGroup.Height = 97;
            this.m_prgGroup.Left = -1;
            this.m_prgGroup.Name = "m_prgGroup";
            this.m_prgGroup.ParentGroup = null;
            this.m_prgGroup.ScreenOwnerName = "DiagPreCheck";
            this.m_prgGroup.Top = 75;
            this.m_prgGroup.VisibleDynamicsValue = true;
            this.m_prgGroup.Width = 353;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.ClientSize = new System.Drawing.Size(345, 188);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(75, 20);
            this.ModalScreen = true;
            this.Name = "DiagPreCheck";
            this.PopupScreen = true;
            this.ScreenID = null;
            this.ScreenTitle = "        Checking";
            this.StyleName = "Default";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_DiagPreCheck = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_DiagPreCheck) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_lblMsg);
            this.DrawingPrimitives.Add(this.m_btnContinue);
            this.DrawingPrimitives.Add(this.m_btnBack);
            this.DrawingPrimitives.Add(this.m_prgDiag);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_lblPrg);
            this.DrawingPrimitives.Add(this.m_prgGroup);
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsg)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnContinue)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnBack)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prgDiag)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblPrg)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_prgGroup)).EndInit();
        }
        
        private void DiagPreCheck_Action_Opened(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("DiagPreCheck", "Opened", "Set Analog", "Tags.CurrentScreen", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.CurrentScreen.SetAnalog(7);
        }
        
        private void m_btnContinue_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnContinue", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        private void m_btnBack_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnBack", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(DiagPreCheck));
            this.m_lblMsg.Text = resources.GetText("DiagPreCheck.lblMsg.Text", "Checking valves and meters...\r\nPlease wait...");
            this.m_lblPrg.Text = resources.GetText("DiagPreCheck.lblPrg.Text", "0 %");
            this.m_btnContinue.Text = resources.GetText("DiagPreCheck.btnContinue.Text", "Continue");
            this.m_btnBack.Text = resources.GetText("DiagPreCheck.btnBack.Text", "EXIT");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_DiagPreCheck) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagProgress"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_prgDiag.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
        }
    }
}
