//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class DiagReportPress : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button21;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle2;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Group;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle3;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Group1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblReport0;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblReport1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblReport2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblReport3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblReport4;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line1;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line2;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line3;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line7;
        
        private bool m_Initialized_DiagReportPress;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf1;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf2;
        
        public DiagReportPress() {
            this.InitializeComponent();
            this.Group.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Group_MouseDown);
            this.Group1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Group1_MouseDown);
            this.Adapter.Opened += new System.EventHandler(this.DiagReportPress_Opened);
            this.Opened += new System.EventHandler(this.DiagReportPress_Action_Opened);
            this.m_Button21.Click += new System.EventHandler(this.m_Button21_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button21 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button21);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Group {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Group);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Group1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Group1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblReport0 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblReport0);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblReport1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblReport1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblReport2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblReport2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblReport3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblReport3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblReport4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblReport4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line7);
            }
        }
        
        private void InitializeComponent() {
            this.brushdynamicsconvertercf2 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval1 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval2 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval3 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval4 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval5 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval6 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Rectangle1 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Button21 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Rectangle2 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Group = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Rectangle3 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Group1 = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text4 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text5 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblReport0 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblReport1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblReport2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblReport3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblReport4 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Line = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line1 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line2 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line3 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line7 = new Neo.ApplicationFramework.Controls.Controls.Line();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button21)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblReport0)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblReport1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblReport2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblReport3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblReport4)).BeginInit();
            this.SuspendLayout();
            // 
            // DiagReportPress
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Text
            // 
            this.m_Text.AutoSize = false;
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.Bold = true;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontFamily = "Arial";
            this.m_Text.FontSizePixels = 20;
            this.m_Text.Height = 30;
            this.m_Text.Left = -4;
            this.m_Text.Name = "m_Text";
            this.m_Text.ScreenOwnerName = "DiagReportPress";
            this.m_Text.TextHorizontalAlignment = "Center";
            this.m_Text.TextVerticalAlignment = "Center";
            this.m_Text.Top = 1;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 480;
            // 
            // m_Rectangle1
            // 
            this.m_Rectangle1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle1.BlinkDynamicsValue = false;
            this.m_Rectangle1.EnabledDynamicsValue = true;
            this.m_Rectangle1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207))))), System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            this.m_Rectangle1.Height = 226;
            this.m_Rectangle1.Left = 123;
            this.m_Rectangle1.Name = "m_Rectangle1";
            this.m_Rectangle1.ScreenOwnerName = "DiagReportPress";
            this.m_Rectangle1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.StrokeThickness = 2;
            this.m_Rectangle1.Top = 38;
            this.m_Rectangle1.VisibleDynamicsValue = true;
            this.m_Rectangle1.Width = 353;
            // 
            // m_Button21
            // 
            this.m_Button21.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button21.BlinkDynamicsValue = false;
            this.m_Button21.Bold = true;
            this.m_Button21.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button21.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button21.EnabledDynamicsValue = true;
            this.m_Button21.FontFamily = "Arial";
            this.m_Button21.FontSizePixels = 16;
            this.m_Button21.ForceTransparency = true;
            this.m_Button21.Height = 47;
            this.m_Button21.IndicatorMargin = null;
            this.m_Button21.Left = 8;
            this.m_Button21.Name = "m_Button21";
            this.m_Button21.RequiresTransparency = true;
            this.m_Button21.ScreenOwnerName = "DiagReportPress";
            this.m_Button21.StyleName = "Chrome";
            this.m_Button21.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button21.SymbolName = "";
            this.m_Button21.TextHeight = 19;
            this.m_Button21.TextValue = 0D;
            this.m_Button21.TextWidth = 101;
            this.m_Button21.Top = 219;
            this.m_Button21.Value = 0D;
            this.m_Button21.VisibleDynamicsValue = true;
            this.m_Button21.VisualPropertiesHashCode = 2126007191;
            this.m_Button21.Width = 107;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.Bold = true;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 16;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 76;
            this.m_Button.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 4D, 4D, 3D);
            this.m_Button.ImageVerticalAlignment = "Bottom";
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 0;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "DiagReportPress";
            this.m_Button.StyleName = "Glossy";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button.SymbolName = "";
            this.m_Button.TextHeight = 19;
            this.m_Button.TextMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(0D, 10D, 0D, 0D);
            this.m_Button.TextValue = 0D;
            this.m_Button.TextVerticalAlignment = "Top";
            this.m_Button.TextWidth = 105;
            this.m_Button.Top = 0;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -140388809;
            this.m_Button.Width = 107;
            // 
            // m_Rectangle2
            // 
            this.m_Rectangle2.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_Rectangle2.BlinkDynamicsValue = false;
            brushdynamicsconvertercf1.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Orange, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval1.End = 1D;
            brushcfinterval1.Start = 1D;
            brushcfinterval1.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Orange, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval2.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(23)))), ((int)(((byte)(54)))), ((int)(((byte)(93))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval3.End = 4D;
            brushcfinterval3.Start = 2D;
            brushcfinterval3.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(23)))), ((int)(((byte)(54)))), ((int)(((byte)(93))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval1);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval2);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval3);
            this.m_Rectangle2.EnabledDynamicsValue = true;
            this.m_Rectangle2.Fill = null;
            this.m_Rectangle2.Height = 8;
            this.m_Rectangle2.Left = 19;
            this.m_Rectangle2.Name = "m_Rectangle2";
            this.m_Rectangle2.ScreenOwnerName = "DiagReportPress";
            this.m_Rectangle2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle2.Top = 48;
            this.m_Rectangle2.VisibleDynamicsValue = true;
            this.m_Rectangle2.Width = 70;
            // 
            // m_Group
            // 
            this.m_Group.BlinkDynamicsValue = false;
            this.m_Group.Components.Add(this.m_Button);
            this.m_Group.Components.Add(this.m_Rectangle2);
            this.m_Group.EnabledDynamicsValue = true;
            this.m_Group.Height = 76;
            this.m_Group.Left = 8;
            this.m_Group.Name = "m_Group";
            this.m_Group.ParentGroup = null;
            this.m_Group.ScreenOwnerName = "DiagReportPress";
            this.m_Group.Top = 40;
            this.m_Group.VisibleDynamicsValue = true;
            this.m_Group.Width = 107;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.Bold = true;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontSizePixels = 16;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Height = 76;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 0;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "DiagReportPress";
            this.m_Button1.StyleName = "Glossy";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button1.TextHeight = 19;
            this.m_Button1.TextMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(0D, 10D, 0D, 0D);
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextVerticalAlignment = "Top";
            this.m_Button1.TextWidth = 105;
            this.m_Button1.Top = 0;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = 139018981;
            this.m_Button1.Width = 107;
            // 
            // m_Rectangle3
            // 
            this.m_Rectangle3.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_Rectangle3.BlinkDynamicsValue = false;
            brushdynamicsconvertercf2.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Orange, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval4.End = 2D;
            brushcfinterval4.Start = 2D;
            brushcfinterval4.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Orange, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval5.End = 1D;
            brushcfinterval5.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(23)))), ((int)(((byte)(54)))), ((int)(((byte)(93))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval6.End = 4D;
            brushcfinterval6.Start = 3D;
            brushcfinterval6.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(23)))), ((int)(((byte)(54)))), ((int)(((byte)(93))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval4);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval5);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval6);
            this.m_Rectangle3.EnabledDynamicsValue = true;
            this.m_Rectangle3.Fill = null;
            this.m_Rectangle3.Height = 8;
            this.m_Rectangle3.Left = 18;
            this.m_Rectangle3.Name = "m_Rectangle3";
            this.m_Rectangle3.ScreenOwnerName = "DiagReportPress";
            this.m_Rectangle3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle3.Top = 45;
            this.m_Rectangle3.VisibleDynamicsValue = true;
            this.m_Rectangle3.Width = 70;
            // 
            // m_Group1
            // 
            this.m_Group1.BlinkDynamicsValue = false;
            this.m_Group1.Components.Add(this.m_Button1);
            this.m_Group1.Components.Add(this.m_Rectangle3);
            this.m_Group1.EnabledDynamicsValue = true;
            this.m_Group1.Height = 76;
            this.m_Group1.Left = 8;
            this.m_Group1.Name = "m_Group1";
            this.m_Group1.ParentGroup = null;
            this.m_Group1.ScreenOwnerName = "DiagReportPress";
            this.m_Group1.Top = 129;
            this.m_Group1.VisibleDynamicsValue = true;
            this.m_Group1.Width = 107;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 18;
            this.m_Text1.Height = 21;
            this.m_Text1.Left = 181;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.ScreenOwnerName = "DiagReportPress";
            this.m_Text1.Top = 44;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 49;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 18;
            this.m_Text2.Height = 21;
            this.m_Text2.Left = 163;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.ScreenOwnerName = "DiagReportPress";
            this.m_Text2.Top = 90;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 70;
            // 
            // m_Text3
            // 
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontSizePixels = 18;
            this.m_Text3.Height = 21;
            this.m_Text3.Left = 159;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.ScreenOwnerName = "DiagReportPress";
            this.m_Text3.Top = 137;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 75;
            // 
            // m_Text4
            // 
            this.m_Text4.BlinkDynamicsValue = false;
            this.m_Text4.EnabledDynamicsValue = true;
            this.m_Text4.FontSizePixels = 18;
            this.m_Text4.Height = 21;
            this.m_Text4.Left = 149;
            this.m_Text4.Name = "m_Text4";
            this.m_Text4.ScreenOwnerName = "DiagReportPress";
            this.m_Text4.Top = 182;
            this.m_Text4.VisibleDynamicsValue = true;
            this.m_Text4.Width = 83;
            // 
            // m_Text5
            // 
            this.m_Text5.BlinkDynamicsValue = false;
            this.m_Text5.EnabledDynamicsValue = true;
            this.m_Text5.FontSizePixels = 18;
            this.m_Text5.Height = 21;
            this.m_Text5.Left = 134;
            this.m_Text5.Name = "m_Text5";
            this.m_Text5.ScreenOwnerName = "DiagReportPress";
            this.m_Text5.Top = 224;
            this.m_Text5.VisibleDynamicsValue = true;
            this.m_Text5.Width = 105;
            // 
            // m_lblReport0
            // 
            this.m_lblReport0.AutoSize = false;
            this.m_lblReport0.BlinkDynamicsValue = false;
            this.m_lblReport0.EnabledDynamicsValue = true;
            this.m_lblReport0.FontSizePixels = 18;
            this.m_lblReport0.Height = 44;
            this.m_lblReport0.Left = 308;
            this.m_lblReport0.Name = "m_lblReport0";
            this.m_lblReport0.ScreenOwnerName = "DiagReportPress";
            this.m_lblReport0.TextHorizontalAlignment = "Center";
            this.m_lblReport0.TextVerticalAlignment = "Center";
            this.m_lblReport0.Top = 39;
            this.m_lblReport0.VisibleDynamicsValue = true;
            this.m_lblReport0.Width = 167;
            // 
            // m_lblReport1
            // 
            this.m_lblReport1.AutoSize = false;
            this.m_lblReport1.BlinkDynamicsValue = false;
            this.m_lblReport1.EnabledDynamicsValue = true;
            this.m_lblReport1.FontSizePixels = 18;
            this.m_lblReport1.Height = 47;
            this.m_lblReport1.Left = 308;
            this.m_lblReport1.Name = "m_lblReport1";
            this.m_lblReport1.ScreenOwnerName = "DiagReportPress";
            this.m_lblReport1.TextHorizontalAlignment = "Center";
            this.m_lblReport1.TextVerticalAlignment = "Center";
            this.m_lblReport1.Top = 84;
            this.m_lblReport1.VisibleDynamicsValue = true;
            this.m_lblReport1.Width = 167;
            // 
            // m_lblReport2
            // 
            this.m_lblReport2.AutoSize = false;
            this.m_lblReport2.BlinkDynamicsValue = false;
            this.m_lblReport2.EnabledDynamicsValue = true;
            this.m_lblReport2.FontSizePixels = 18;
            this.m_lblReport2.Height = 45;
            this.m_lblReport2.Left = 308;
            this.m_lblReport2.Name = "m_lblReport2";
            this.m_lblReport2.ScreenOwnerName = "DiagReportPress";
            this.m_lblReport2.TextHorizontalAlignment = "Center";
            this.m_lblReport2.TextVerticalAlignment = "Center";
            this.m_lblReport2.Top = 132;
            this.m_lblReport2.VisibleDynamicsValue = true;
            this.m_lblReport2.Width = 167;
            // 
            // m_lblReport3
            // 
            this.m_lblReport3.AutoSize = false;
            this.m_lblReport3.BlinkDynamicsValue = false;
            this.m_lblReport3.EnabledDynamicsValue = true;
            this.m_lblReport3.FontSizePixels = 18;
            this.m_lblReport3.Height = 42;
            this.m_lblReport3.Left = 308;
            this.m_lblReport3.Name = "m_lblReport3";
            this.m_lblReport3.ScreenOwnerName = "DiagReportPress";
            this.m_lblReport3.TextHorizontalAlignment = "Center";
            this.m_lblReport3.TextVerticalAlignment = "Center";
            this.m_lblReport3.Top = 178;
            this.m_lblReport3.VisibleDynamicsValue = true;
            this.m_lblReport3.Width = 167;
            // 
            // m_lblReport4
            // 
            this.m_lblReport4.AutoSize = false;
            this.m_lblReport4.BlinkDynamicsValue = false;
            this.m_lblReport4.EnabledDynamicsValue = true;
            this.m_lblReport4.FontSizePixels = 18;
            this.m_lblReport4.Height = 42;
            this.m_lblReport4.Left = 308;
            this.m_lblReport4.Name = "m_lblReport4";
            this.m_lblReport4.ScreenOwnerName = "DiagReportPress";
            this.m_lblReport4.TextHorizontalAlignment = "Center";
            this.m_lblReport4.TextVerticalAlignment = "Center";
            this.m_lblReport4.Top = 221;
            this.m_lblReport4.VisibleDynamicsValue = true;
            this.m_lblReport4.Width = 167;
            // 
            // m_Line
            // 
            this.m_Line.BlinkDynamicsValue = false;
            this.m_Line.EnabledDynamicsValue = true;
            this.m_Line.Fill = null;
            this.m_Line.Name = "m_Line";
            this.m_Line.ScreenOwnerName = "DiagReportPress";
            this.m_Line.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line.VisibleDynamicsValue = true;
            this.m_Line.X1 = 124;
            this.m_Line.X2 = 475;
            this.m_Line.Y1 = 83;
            this.m_Line.Y2 = 83;
            // 
            // m_Line1
            // 
            this.m_Line1.BlinkDynamicsValue = false;
            this.m_Line1.EnabledDynamicsValue = true;
            this.m_Line1.Fill = null;
            this.m_Line1.Name = "m_Line1";
            this.m_Line1.ScreenOwnerName = "DiagReportPress";
            this.m_Line1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line1.VisibleDynamicsValue = true;
            this.m_Line1.X1 = 123;
            this.m_Line1.X2 = 476;
            this.m_Line1.Y1 = 131;
            this.m_Line1.Y2 = 131;
            // 
            // m_Line2
            // 
            this.m_Line2.BlinkDynamicsValue = false;
            this.m_Line2.EnabledDynamicsValue = true;
            this.m_Line2.Fill = null;
            this.m_Line2.Name = "m_Line2";
            this.m_Line2.ScreenOwnerName = "DiagReportPress";
            this.m_Line2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line2.VisibleDynamicsValue = true;
            this.m_Line2.X1 = 124;
            this.m_Line2.X2 = 476;
            this.m_Line2.Y1 = 177;
            this.m_Line2.Y2 = 177;
            // 
            // m_Line3
            // 
            this.m_Line3.BlinkDynamicsValue = false;
            this.m_Line3.EnabledDynamicsValue = true;
            this.m_Line3.Fill = null;
            this.m_Line3.Name = "m_Line3";
            this.m_Line3.ScreenOwnerName = "DiagReportPress";
            this.m_Line3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line3.VisibleDynamicsValue = true;
            this.m_Line3.X1 = 124;
            this.m_Line3.X2 = 476;
            this.m_Line3.Y1 = 220;
            this.m_Line3.Y2 = 220;
            // 
            // m_Line7
            // 
            this.m_Line7.BlinkDynamicsValue = false;
            this.m_Line7.EnabledDynamicsValue = true;
            this.m_Line7.Fill = null;
            this.m_Line7.Name = "m_Line7";
            this.m_Line7.ScreenOwnerName = "DiagReportPress";
            this.m_Line7.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line7.VisibleDynamicsValue = true;
            this.m_Line7.X1 = 307;
            this.m_Line7.X2 = 307;
            this.m_Line7.Y1 = 38;
            this.m_Line7.Y2 = 263;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(480, 272);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "DiagReportPress";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_DiagReportPress = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_DiagReportPress) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Rectangle1);
            this.DrawingPrimitives.Add(this.m_Button21);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Rectangle2);
            this.DrawingPrimitives.Add(this.m_Group);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Rectangle3);
            this.DrawingPrimitives.Add(this.m_Group1);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_Text3);
            this.DrawingPrimitives.Add(this.m_Text4);
            this.DrawingPrimitives.Add(this.m_Text5);
            this.DrawingPrimitives.Add(this.m_lblReport0);
            this.DrawingPrimitives.Add(this.m_lblReport1);
            this.DrawingPrimitives.Add(this.m_lblReport2);
            this.DrawingPrimitives.Add(this.m_lblReport3);
            this.DrawingPrimitives.Add(this.m_lblReport4);
            this.DrawingPrimitives.Add(this.m_Line);
            this.DrawingPrimitives.Add(this.m_Line1);
            this.DrawingPrimitives.Add(this.m_Line2);
            this.DrawingPrimitives.Add(this.m_Line3);
            this.DrawingPrimitives.Add(this.m_Line7);
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button21)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblReport0)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblReport1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblReport2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblReport3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblReport4)).EndInit();
        }
        
        private void DiagReportPress_Action_Opened(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("DiagReportPress", "Opened", "Set Analog", "Tags.CurrentScreen", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.CurrentScreen.SetAnalog(9);
        }
        
        private void m_Button21_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button21", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
            this.LogClose("m_Button21", "Click", "Close Screen", "");
            this.Close();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(DiagReportPress));
            this.m_Text.Text = resources.GetText("DiagReportPress.Text.Text", "PRESSURE SENSORS INFO");
            this.m_Button21.Text = resources.GetText("DiagReportPress.Button21.Text", "OK");
            this.m_Button.Text = resources.GetText("DiagReportPress.Button.Text", "INLET");
            this.m_Button1.Text = resources.GetText("DiagReportPress.Button1.Text", "TEST");
            this.m_Text1.Text = resources.GetText("DiagReportPress.Text1.Text", "Pressure");
            this.m_Text2.Text = resources.GetText("DiagReportPress.Text2.Text", "Temperature");
            this.m_Text3.Text = resources.GetText("DiagReportPress.Text3.Text", "Error Register");
            this.m_Text4.Text = resources.GetText("DiagReportPress.Text4.Text", "Pressure Status");
            this.m_Text5.Text = resources.GetText("DiagReportPress.Text5.Text", "Temperature Status");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_DiagReportPress) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Fill", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SettingSel"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf2);
            this.m_Rectangle3.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Fill", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.SettingSel"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf1);
            this.m_Rectangle2.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
        }
    }
}
