//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class DiagScreen : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.ProgressBar m_pbDiag1;
        
        private Neo.ApplicationFramework.Controls.Controls.ProgressBar m_pbDiag2;
        
        private Neo.ApplicationFramework.Controls.Controls.ProgressBar m_pbDiag3;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle1;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button11;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblMsgSmall1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblMsgSmall2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblMsgSmall3;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnDetail1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnDetail2;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnDetail3;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text4;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line2;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line3;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text6;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnSave;
        
        private Neo.ApplicationFramework.Controls.Symbol.AnimatedPictureCF m_LoadGif1;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_picDiag1;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_picDiag2;
        
        private Neo.ApplicationFramework.Controls.Symbol.SymbolCF m_picDiag3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblMsgBig1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblMsgBig2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_lblMsgBig3;
        
        private Neo.ApplicationFramework.Controls.Symbol.AnimatedPictureCF m_LoadGif2;
        
        private Neo.ApplicationFramework.Controls.Symbol.AnimatedPictureCF m_LoadGif3;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private bool m_Initialized_DiagScreen;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf1;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf2;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf3;
        
        public DiagScreen() {
            this.InitializeComponent();
            this.Button11.Click += new System.EventHandler(this.Button11_Click);
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            this.Adapter.Closed += new System.EventHandler(this.DiagScreen_Closed);
            this.Adapter.Opened += new System.EventHandler(this.DiagScreen_Opened);
            this.Opened += new System.EventHandler(this.DiagScreen_Action_Opened);
            this.m_Button11.Click += new System.EventHandler(this.m_Button11_Action_Click);
            this.m_btnDetail1.Click += new System.EventHandler(this.m_btnDetail1_Action_Click);
            this.m_btnDetail2.Click += new System.EventHandler(this.m_btnDetail2_Action_Click);
            this.m_btnDetail3.Click += new System.EventHandler(this.m_btnDetail3_Action_Click);
            this.m_btnSave.Click += new System.EventHandler(this.m_btnSave_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button11 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button11);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblMsgSmall1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblMsgSmall1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblMsgSmall2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblMsgSmall2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblMsgSmall3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblMsgSmall3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnDetail1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnDetail1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnDetail2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnDetail2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnDetail3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnDetail3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ProgressBarCFAdapter pbDiag1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ProgressBarCFAdapter>(this.m_pbDiag1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnSave {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnSave);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter LoadGif1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_LoadGif1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ProgressBarCFAdapter pbDiag2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ProgressBarCFAdapter>(this.m_pbDiag2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter picDiag1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_picDiag1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter picDiag2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_picDiag2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter picDiag3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_picDiag3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblMsgBig1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblMsgBig1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblMsgBig2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblMsgBig2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter lblMsgBig3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_lblMsgBig3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ProgressBarCFAdapter pbDiag3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ProgressBarCFAdapter>(this.m_pbDiag3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter LoadGif2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_LoadGif2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter LoadGif3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_LoadGif3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        private void InitializeComponent() {
            this.brushdynamicsconvertercf3 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf2 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem1 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem2 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem3 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem4 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem5 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem6 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem7 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem8 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.SymbolInterval symbolinterval9 = new Neo.ApplicationFramework.Common.Dynamics.SymbolInterval();
            Neo.ApplicationFramework.Common.MultiSymbolItem multisymbolitem9 = new Neo.ApplicationFramework.Common.MultiSymbolItem();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval1 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval2 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval3 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval4 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval5 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval6 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval7 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval8 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval9 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            this.m_pbDiag1 = new Neo.ApplicationFramework.Controls.Controls.ProgressBar();
            this.m_pbDiag2 = new Neo.ApplicationFramework.Controls.Controls.ProgressBar();
            this.m_pbDiag3 = new Neo.ApplicationFramework.Controls.Controls.ProgressBar();
            this.m_Rectangle1 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button11 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_lblMsgSmall1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblMsgSmall2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblMsgSmall3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_btnDetail1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnDetail2 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnDetail3 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Line = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line1 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Text4 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Line2 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line3 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Line4 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Text5 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text6 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_btnSave = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_LoadGif1 = new Neo.ApplicationFramework.Controls.Symbol.AnimatedPictureCF();
            this.m_picDiag1 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_picDiag2 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_picDiag3 = new Neo.ApplicationFramework.Controls.Symbol.SymbolCF();
            this.m_lblMsgBig1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblMsgBig2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_lblMsgBig3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_LoadGif2 = new Neo.ApplicationFramework.Controls.Symbol.AnimatedPictureCF();
            this.m_LoadGif3 = new Neo.ApplicationFramework.Controls.Symbol.AnimatedPictureCF();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsgSmall1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsgSmall2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsgSmall3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnDetail1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnDetail2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnDetail3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnSave)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_LoadGif1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_picDiag1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_picDiag2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_picDiag3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsgBig1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsgBig2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsgBig3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_LoadGif2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_LoadGif3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            this.SuspendLayout();
            // 
            // DiagScreen
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227))))), System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_pbDiag1
            // 
            this.m_pbDiag1.BarColor = System.Drawing.Color.Lime;
            this.m_pbDiag1.BarGradientColor = System.Drawing.Color.Lime;
            this.m_pbDiag1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.m_pbDiag1.DrawStyle = OpenNETCF.Windows.Forms.DrawStyle.Solid;
            this.m_pbDiag1.EnabledDynamicsValue = true;
            this.m_pbDiag1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(176)))), ((int)(((byte)(37)))));
            this.m_pbDiag1.Location = new System.Drawing.Point(90, 88);
            this.m_pbDiag1.Maximum = 100;
            this.m_pbDiag1.Minimum = 0;
            this.m_pbDiag1.Name = "m_pbDiag1";
            this.m_pbDiag1.ShowPercentValueText = false;
            this.m_pbDiag1.ShowValueText = false;
            this.m_pbDiag1.Size = new System.Drawing.Size(253, 21);
            this.m_pbDiag1.Step = 0;
            this.m_pbDiag1.TabIndex = 2147483647;
            this.m_pbDiag1.Value = 0;
            this.m_pbDiag1.VisibleDynamicsValue = true;
            // 
            // m_pbDiag2
            // 
            this.m_pbDiag2.BarColor = System.Drawing.Color.Lime;
            this.m_pbDiag2.BarGradientColor = System.Drawing.Color.Lime;
            this.m_pbDiag2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.m_pbDiag2.DrawStyle = OpenNETCF.Windows.Forms.DrawStyle.Solid;
            this.m_pbDiag2.EnabledDynamicsValue = true;
            this.m_pbDiag2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(176)))), ((int)(((byte)(37)))));
            this.m_pbDiag2.Location = new System.Drawing.Point(91, 137);
            this.m_pbDiag2.Maximum = 100;
            this.m_pbDiag2.Minimum = 0;
            this.m_pbDiag2.Name = "m_pbDiag2";
            this.m_pbDiag2.ShowPercentValueText = false;
            this.m_pbDiag2.ShowValueText = false;
            this.m_pbDiag2.Size = new System.Drawing.Size(251, 21);
            this.m_pbDiag2.Step = 0;
            this.m_pbDiag2.TabIndex = 2147483647;
            this.m_pbDiag2.Value = 0;
            this.m_pbDiag2.VisibleDynamicsValue = true;
            // 
            // m_pbDiag3
            // 
            this.m_pbDiag3.BarColor = System.Drawing.Color.Lime;
            this.m_pbDiag3.BarGradientColor = System.Drawing.Color.Lime;
            this.m_pbDiag3.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.m_pbDiag3.DrawStyle = OpenNETCF.Windows.Forms.DrawStyle.Solid;
            this.m_pbDiag3.EnabledDynamicsValue = true;
            this.m_pbDiag3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(176)))), ((int)(((byte)(37)))));
            this.m_pbDiag3.Location = new System.Drawing.Point(91, 186);
            this.m_pbDiag3.Maximum = 100;
            this.m_pbDiag3.Minimum = 0;
            this.m_pbDiag3.Name = "m_pbDiag3";
            this.m_pbDiag3.ShowPercentValueText = false;
            this.m_pbDiag3.ShowValueText = false;
            this.m_pbDiag3.Size = new System.Drawing.Size(251, 21);
            this.m_pbDiag3.Step = 0;
            this.m_pbDiag3.TabIndex = 2147483647;
            this.m_pbDiag3.Value = 0;
            this.m_pbDiag3.VisibleDynamicsValue = true;
            // 
            // m_Rectangle1
            // 
            this.m_Rectangle1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle1.BlinkDynamicsValue = false;
            this.m_Rectangle1.EnabledDynamicsValue = true;
            this.m_Rectangle1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Height = 167;
            this.m_Rectangle1.Left = 14;
            this.m_Rectangle1.Name = "m_Rectangle1";
            this.m_Rectangle1.ScreenOwnerName = "DiagScreen";
            this.m_Rectangle1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Top = 44;
            this.m_Rectangle1.VisibleDynamicsValue = true;
            this.m_Rectangle1.Width = 450;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Height = 42;
            this.m_Rectangle.Left = -4;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "DiagScreen";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Top = -5;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 485;
            // 
            // m_Text
            // 
            this.m_Text.AutoSize = false;
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.Bold = true;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontFamily = "Arial";
            this.m_Text.FontSizePixels = 20;
            this.m_Text.Height = 30;
            this.m_Text.Left = -4;
            this.m_Text.Name = "m_Text";
            this.m_Text.ScreenOwnerName = "DiagScreen";
            this.m_Text.TextHorizontalAlignment = "Center";
            this.m_Text.TextVerticalAlignment = "Center";
            this.m_Text.Top = 1;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 480;
            // 
            // m_Button11
            // 
            this.m_Button11.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button11.BlinkDynamicsValue = false;
            this.m_Button11.Bold = true;
            this.m_Button11.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button11.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button11.EnabledDynamicsValue = true;
            this.m_Button11.FontFamily = "Arial";
            this.m_Button11.FontSizePixels = 16;
            this.m_Button11.ForceTransparency = true;
            this.m_Button11.Height = 47;
            this.m_Button11.IndicatorMargin = null;
            this.m_Button11.Left = 14;
            this.m_Button11.Name = "m_Button11";
            this.m_Button11.RequiresTransparency = true;
            this.m_Button11.ScreenOwnerName = "DiagScreen";
            this.m_Button11.StyleName = "Chrome";
            this.m_Button11.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button11.SymbolName = "";
            this.m_Button11.TextHeight = 19;
            this.m_Button11.TextValue = 0D;
            this.m_Button11.TextWidth = 101;
            this.m_Button11.Top = 220;
            this.m_Button11.Value = 0D;
            this.m_Button11.VisibleDynamicsValue = true;
            this.m_Button11.VisualPropertiesHashCode = 2126007191;
            this.m_Button11.Width = 107;
            // 
            // m_lblMsgSmall1
            // 
            this.m_lblMsgSmall1.AutoSize = false;
            this.m_lblMsgSmall1.BlinkDynamicsValue = false;
            this.m_lblMsgSmall1.Bold = true;
            this.m_lblMsgSmall1.EnabledDynamicsValue = true;
            this.m_lblMsgSmall1.FontFamily = "Arial";
            this.m_lblMsgSmall1.FontSizePixels = 14;
            this.m_lblMsgSmall1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.m_lblMsgSmall1.Height = 39;
            this.m_lblMsgSmall1.Left = 87;
            this.m_lblMsgSmall1.Name = "m_lblMsgSmall1";
            this.m_lblMsgSmall1.ScreenOwnerName = "DiagScreen";
            this.m_lblMsgSmall1.Top = 66;
            this.m_lblMsgSmall1.VisibleDynamicsValue = true;
            this.m_lblMsgSmall1.Width = 257;
            // 
            // m_lblMsgSmall2
            // 
            this.m_lblMsgSmall2.AutoSize = false;
            this.m_lblMsgSmall2.BlinkDynamicsValue = false;
            this.m_lblMsgSmall2.Bold = true;
            this.m_lblMsgSmall2.EnabledDynamicsValue = true;
            this.m_lblMsgSmall2.FontFamily = "Arial";
            this.m_lblMsgSmall2.FontSizePixels = 14;
            this.m_lblMsgSmall2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.m_lblMsgSmall2.Height = 39;
            this.m_lblMsgSmall2.Left = 87;
            this.m_lblMsgSmall2.Name = "m_lblMsgSmall2";
            this.m_lblMsgSmall2.ScreenOwnerName = "DiagScreen";
            this.m_lblMsgSmall2.Top = 116;
            this.m_lblMsgSmall2.VisibleDynamicsValue = true;
            this.m_lblMsgSmall2.Width = 262;
            // 
            // m_lblMsgSmall3
            // 
            this.m_lblMsgSmall3.AutoSize = false;
            this.m_lblMsgSmall3.BlinkDynamicsValue = false;
            this.m_lblMsgSmall3.Bold = true;
            this.m_lblMsgSmall3.EnabledDynamicsValue = true;
            this.m_lblMsgSmall3.FontFamily = "Arial";
            this.m_lblMsgSmall3.FontSizePixels = 14;
            this.m_lblMsgSmall3.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.m_lblMsgSmall3.Height = 39;
            this.m_lblMsgSmall3.Left = 87;
            this.m_lblMsgSmall3.Name = "m_lblMsgSmall3";
            this.m_lblMsgSmall3.ScreenOwnerName = "DiagScreen";
            this.m_lblMsgSmall3.Top = 165;
            this.m_lblMsgSmall3.VisibleDynamicsValue = true;
            this.m_lblMsgSmall3.Width = 258;
            // 
            // m_btnDetail1
            // 
            this.m_btnDetail1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(146)))), ((int)(((byte)(214))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnDetail1.BlinkDynamicsValue = false;
            this.m_btnDetail1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnDetail1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnDetail1.EnabledDynamicsValue = true;
            this.m_btnDetail1.FontFamily = "Arial";
            this.m_btnDetail1.FontSizePixels = 18;
            this.m_btnDetail1.ForceTransparency = true;
            this.m_btnDetail1.Height = 45;
            this.m_btnDetail1.IndicatorMargin = null;
            this.m_btnDetail1.Left = 357;
            this.m_btnDetail1.Name = "m_btnDetail1";
            this.m_btnDetail1.RequiresTransparency = true;
            this.m_btnDetail1.ScreenOwnerName = "DiagScreen";
            this.m_btnDetail1.StyleName = "Glossy";
            this.m_btnDetail1.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_btnDetail1.TextHeight = 22;
            this.m_btnDetail1.TextValue = 0D;
            this.m_btnDetail1.TextWidth = 95;
            this.m_btnDetail1.Top = 68;
            this.m_btnDetail1.Value = 0D;
            this.m_btnDetail1.VisibleDynamicsValue = true;
            this.m_btnDetail1.VisualPropertiesHashCode = 2087860494;
            this.m_btnDetail1.Width = 101;
            // 
            // m_btnDetail2
            // 
            this.m_btnDetail2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(146)))), ((int)(((byte)(214))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnDetail2.BlinkDynamicsValue = false;
            this.m_btnDetail2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnDetail2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnDetail2.EnabledDynamicsValue = true;
            this.m_btnDetail2.FontFamily = "Arial";
            this.m_btnDetail2.FontSizePixels = 18;
            this.m_btnDetail2.ForceTransparency = true;
            this.m_btnDetail2.Height = 45;
            this.m_btnDetail2.IndicatorMargin = null;
            this.m_btnDetail2.Left = 357;
            this.m_btnDetail2.Name = "m_btnDetail2";
            this.m_btnDetail2.RequiresTransparency = true;
            this.m_btnDetail2.ScreenOwnerName = "DiagScreen";
            this.m_btnDetail2.StyleName = "Glossy";
            this.m_btnDetail2.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_btnDetail2.TextHeight = 22;
            this.m_btnDetail2.TextValue = 0D;
            this.m_btnDetail2.TextWidth = 95;
            this.m_btnDetail2.Top = 116;
            this.m_btnDetail2.Value = 0D;
            this.m_btnDetail2.VisibleDynamicsValue = true;
            this.m_btnDetail2.VisualPropertiesHashCode = 2087860494;
            this.m_btnDetail2.Width = 101;
            // 
            // m_btnDetail3
            // 
            this.m_btnDetail3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(146)))), ((int)(((byte)(214))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnDetail3.BlinkDynamicsValue = false;
            this.m_btnDetail3.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnDetail3.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnDetail3.EnabledDynamicsValue = true;
            this.m_btnDetail3.FontFamily = "Arial";
            this.m_btnDetail3.FontSizePixels = 18;
            this.m_btnDetail3.ForceTransparency = true;
            this.m_btnDetail3.Height = 45;
            this.m_btnDetail3.IndicatorMargin = null;
            this.m_btnDetail3.Left = 357;
            this.m_btnDetail3.Name = "m_btnDetail3";
            this.m_btnDetail3.RequiresTransparency = true;
            this.m_btnDetail3.ScreenOwnerName = "DiagScreen";
            this.m_btnDetail3.StyleName = "Glossy";
            this.m_btnDetail3.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_btnDetail3.TextHeight = 22;
            this.m_btnDetail3.TextValue = 0D;
            this.m_btnDetail3.TextWidth = 95;
            this.m_btnDetail3.Top = 164;
            this.m_btnDetail3.Value = 0D;
            this.m_btnDetail3.VisibleDynamicsValue = true;
            this.m_btnDetail3.VisualPropertiesHashCode = 2087860494;
            this.m_btnDetail3.Width = 101;
            // 
            // m_Line
            // 
            this.m_Line.BlinkDynamicsValue = false;
            this.m_Line.EnabledDynamicsValue = true;
            this.m_Line.Fill = null;
            this.m_Line.Name = "m_Line";
            this.m_Line.ScreenOwnerName = "DiagScreen";
            this.m_Line.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line.VisibleDynamicsValue = true;
            this.m_Line.X1 = 15;
            this.m_Line.X2 = 463;
            this.m_Line.Y1 = 66;
            this.m_Line.Y2 = 66;
            // 
            // m_Line1
            // 
            this.m_Line1.BlinkDynamicsValue = false;
            this.m_Line1.EnabledDynamicsValue = true;
            this.m_Line1.Fill = null;
            this.m_Line1.Name = "m_Line1";
            this.m_Line1.ScreenOwnerName = "DiagScreen";
            this.m_Line1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line1.VisibleDynamicsValue = true;
            this.m_Line1.X1 = 84;
            this.m_Line1.X2 = 84;
            this.m_Line1.Y1 = 44;
            this.m_Line1.Y2 = 210;
            // 
            // m_Text4
            // 
            this.m_Text4.AutoSize = false;
            this.m_Text4.BlinkDynamicsValue = false;
            this.m_Text4.Bold = true;
            this.m_Text4.EnabledDynamicsValue = true;
            this.m_Text4.FontFamily = "Arial";
            this.m_Text4.FontSizePixels = 12;
            this.m_Text4.Height = 20;
            this.m_Text4.Left = 26;
            this.m_Text4.Name = "m_Text4";
            this.m_Text4.ScreenOwnerName = "DiagScreen";
            this.m_Text4.Top = 44;
            this.m_Text4.VisibleDynamicsValue = true;
            this.m_Text4.Width = 75;
            // 
            // m_Line2
            // 
            this.m_Line2.BlinkDynamicsValue = false;
            this.m_Line2.EnabledDynamicsValue = true;
            this.m_Line2.Fill = null;
            this.m_Line2.Name = "m_Line2";
            this.m_Line2.ScreenOwnerName = "DiagScreen";
            this.m_Line2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line2.VisibleDynamicsValue = true;
            this.m_Line2.X1 = 14;
            this.m_Line2.X2 = 463;
            this.m_Line2.Y1 = 114;
            this.m_Line2.Y2 = 114;
            // 
            // m_Line3
            // 
            this.m_Line3.BlinkDynamicsValue = false;
            this.m_Line3.EnabledDynamicsValue = true;
            this.m_Line3.Fill = null;
            this.m_Line3.Name = "m_Line3";
            this.m_Line3.ScreenOwnerName = "DiagScreen";
            this.m_Line3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line3.VisibleDynamicsValue = true;
            this.m_Line3.X1 = 15;
            this.m_Line3.X2 = 463;
            this.m_Line3.Y1 = 162;
            this.m_Line3.Y2 = 162;
            // 
            // m_Line4
            // 
            this.m_Line4.BlinkDynamicsValue = false;
            this.m_Line4.EnabledDynamicsValue = true;
            this.m_Line4.Fill = null;
            this.m_Line4.Name = "m_Line4";
            this.m_Line4.ScreenOwnerName = "DiagScreen";
            this.m_Line4.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line4.VisibleDynamicsValue = true;
            this.m_Line4.X1 = 352;
            this.m_Line4.X2 = 352;
            this.m_Line4.Y1 = 44;
            this.m_Line4.Y2 = 210;
            // 
            // m_Text5
            // 
            this.m_Text5.AutoSize = false;
            this.m_Text5.BlinkDynamicsValue = false;
            this.m_Text5.Bold = true;
            this.m_Text5.EnabledDynamicsValue = true;
            this.m_Text5.FontFamily = "Arial";
            this.m_Text5.FontSizePixels = 12;
            this.m_Text5.Height = 23;
            this.m_Text5.Left = 90;
            this.m_Text5.Name = "m_Text5";
            this.m_Text5.ScreenOwnerName = "DiagScreen";
            this.m_Text5.TextHorizontalAlignment = "Center";
            this.m_Text5.Top = 44;
            this.m_Text5.VisibleDynamicsValue = true;
            this.m_Text5.Width = 254;
            // 
            // m_Text6
            // 
            this.m_Text6.AutoSize = false;
            this.m_Text6.BlinkDynamicsValue = false;
            this.m_Text6.Bold = true;
            this.m_Text6.EnabledDynamicsValue = true;
            this.m_Text6.FontFamily = "Arial";
            this.m_Text6.FontSizePixels = 12;
            this.m_Text6.Height = 20;
            this.m_Text6.Left = 352;
            this.m_Text6.Name = "m_Text6";
            this.m_Text6.ScreenOwnerName = "DiagScreen";
            this.m_Text6.TextHorizontalAlignment = "Center";
            this.m_Text6.Top = 44;
            this.m_Text6.VisibleDynamicsValue = true;
            this.m_Text6.Width = 110;
            // 
            // m_btnSave
            // 
            this.m_btnSave.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(146)))), ((int)(((byte)(214))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnSave.BlinkDynamicsValue = false;
            this.m_btnSave.Bold = true;
            this.m_btnSave.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnSave.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnSave.EnabledDynamicsValue = true;
            this.m_btnSave.FontFamily = "Arial";
            this.m_btnSave.FontSizePixels = 16;
            this.m_btnSave.ForceTransparency = true;
            this.m_btnSave.Height = 47;
            this.m_btnSave.IndicatorMargin = null;
            this.m_btnSave.Left = 158;
            this.m_btnSave.Name = "m_btnSave";
            this.m_btnSave.RequiresTransparency = true;
            this.m_btnSave.ScreenOwnerName = "DiagScreen";
            this.m_btnSave.StyleName = "Glossy";
            this.m_btnSave.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_btnSave.TextHeight = 19;
            this.m_btnSave.TextValue = 0D;
            this.m_btnSave.TextWidth = 175;
            this.m_btnSave.Top = 220;
            this.m_btnSave.Value = 0D;
            this.m_btnSave.VisibleDynamicsValue = true;
            this.m_btnSave.VisualPropertiesHashCode = 887329061;
            this.m_btnSave.Width = 181;
            // 
            // m_LoadGif1
            // 
            this.m_LoadGif1.BlinkDynamicsValue = false;
            this.m_LoadGif1.EnabledDynamicsValue = true;
            this.m_LoadGif1.Height = 36;
            this.m_LoadGif1.IsAnimationEnabled = true;
            this.m_LoadGif1.Left = 33;
            this.m_LoadGif1.Name = "m_LoadGif1";
            this.m_LoadGif1.ScreenOwnerName = "DiagScreen";
            this.m_LoadGif1.Stretch = true;
            this.m_LoadGif1.SymbolName = "ajax-loader (1)";
            this.m_LoadGif1.Top = 72;
            this.m_LoadGif1.VisibleDynamicsValue = true;
            this.m_LoadGif1.Width = 36;
            // 
            // m_picDiag1
            // 
            this.m_picDiag1.BlinkDynamicsValue = false;
            this.m_picDiag1.EnabledDynamicsValue = true;
            this.m_picDiag1.Height = 37;
            this.m_picDiag1.Left = 31;
            this.m_picDiag1.Name = "m_picDiag1";
            this.m_picDiag1.ScreenOwnerName = "DiagScreen";
            multisymbolitem1.SymbolName = "br_cancel9";
            multisymbolitem1.Transparent = false;
            symbolinterval1.Value = multisymbolitem1;
            symbolinterval2.End = 1D;
            symbolinterval2.Start = 1D;
            multisymbolitem2.SymbolName = "br_ok9";
            multisymbolitem2.Transparent = false;
            symbolinterval2.Value = multisymbolitem2;
            symbolinterval3.End = 2D;
            symbolinterval3.Start = 2D;
            multisymbolitem3.SymbolName = "warning";
            multisymbolitem3.Transparent = false;
            symbolinterval3.Value = multisymbolitem3;
            symbolintervalmapper6.Intervals.Add(symbolinterval1);
            symbolintervalmapper6.Intervals.Add(symbolinterval2);
            symbolintervalmapper6.Intervals.Add(symbolinterval3);
            this.m_picDiag1.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_picDiag1.SymbolName = "br_cancel9";
            this.m_picDiag1.Top = 72;
            this.m_picDiag1.Value = 0D;
            this.m_picDiag1.VisibleDynamicsValue = true;
            this.m_picDiag1.Width = 38;
            // 
            // m_picDiag2
            // 
            this.m_picDiag2.BlinkDynamicsValue = false;
            this.m_picDiag2.EnabledDynamicsValue = true;
            this.m_picDiag2.Height = 37;
            this.m_picDiag2.Left = 31;
            this.m_picDiag2.Name = "m_picDiag2";
            this.m_picDiag2.ScreenOwnerName = "DiagScreen";
            multisymbolitem4.SymbolName = "br_cancel9";
            multisymbolitem4.Transparent = false;
            symbolinterval4.Value = multisymbolitem4;
            symbolinterval5.End = 1D;
            symbolinterval5.Start = 1D;
            multisymbolitem5.SymbolName = "br_ok9";
            multisymbolitem5.Transparent = false;
            symbolinterval5.Value = multisymbolitem5;
            symbolinterval6.End = 2D;
            symbolinterval6.Start = 2D;
            multisymbolitem6.SymbolName = "warning";
            multisymbolitem6.Transparent = false;
            symbolinterval6.Value = multisymbolitem6;
            symbolintervalmapper7.Intervals.Add(symbolinterval4);
            symbolintervalmapper7.Intervals.Add(symbolinterval5);
            symbolintervalmapper7.Intervals.Add(symbolinterval6);
            this.m_picDiag2.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_picDiag2.SymbolName = "br_cancel9";
            this.m_picDiag2.Top = 120;
            this.m_picDiag2.Value = 0D;
            this.m_picDiag2.VisibleDynamicsValue = true;
            this.m_picDiag2.Width = 38;
            // 
            // m_picDiag3
            // 
            this.m_picDiag3.BlinkDynamicsValue = false;
            this.m_picDiag3.EnabledDynamicsValue = true;
            this.m_picDiag3.Height = 37;
            this.m_picDiag3.Left = 31;
            this.m_picDiag3.Name = "m_picDiag3";
            this.m_picDiag3.ScreenOwnerName = "DiagScreen";
            multisymbolitem7.SymbolName = "br_cancel9";
            multisymbolitem7.Transparent = false;
            symbolinterval7.Value = multisymbolitem7;
            symbolinterval8.End = 1D;
            symbolinterval8.Start = 1D;
            multisymbolitem8.SymbolName = "br_ok9";
            multisymbolitem8.Transparent = false;
            symbolinterval8.Value = multisymbolitem8;
            symbolinterval9.End = 2D;
            symbolinterval9.Start = 2D;
            multisymbolitem9.SymbolName = "warning";
            multisymbolitem9.Transparent = false;
            symbolinterval9.Value = multisymbolitem9;
            symbolintervalmapper8.Intervals.Add(symbolinterval7);
            symbolintervalmapper8.Intervals.Add(symbolinterval8);
            symbolintervalmapper8.Intervals.Add(symbolinterval9);
            this.m_picDiag3.SymbolIntervalMapper = symbolintervalmapper8;
            this.m_picDiag3.SymbolName = "br_cancel9";
            this.m_picDiag3.Top = 168;
            this.m_picDiag3.Value = 0D;
            this.m_picDiag3.VisibleDynamicsValue = true;
            this.m_picDiag3.Width = 38;
            // 
            // m_lblMsgBig1
            // 
            this.m_lblMsgBig1.AutoSize = false;
            this.m_lblMsgBig1.BlinkDynamicsValue = false;
            this.m_lblMsgBig1.Bold = true;
            brushdynamicsconvertercf1.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Green, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval1.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(28)))), ((int)(((byte)(36))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval2.End = 1D;
            brushcfinterval2.Start = 1D;
            brushcfinterval2.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Green, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval3.End = 2D;
            brushcfinterval3.Start = 2D;
            brushcfinterval3.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(194)))), ((int)(((byte)(14))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval1);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval2);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval3);
            this.m_lblMsgBig1.EnabledDynamicsValue = true;
            this.m_lblMsgBig1.FontFamily = "Arial";
            this.m_lblMsgBig1.FontSizePixels = 16;
            this.m_lblMsgBig1.Height = 32;
            this.m_lblMsgBig1.Left = 89;
            this.m_lblMsgBig1.Name = "m_lblMsgBig1";
            this.m_lblMsgBig1.ScreenOwnerName = "DiagScreen";
            this.m_lblMsgBig1.Top = 75;
            this.m_lblMsgBig1.VisibleDynamicsValue = true;
            this.m_lblMsgBig1.Width = 260;
            // 
            // m_lblMsgBig2
            // 
            this.m_lblMsgBig2.AutoSize = false;
            this.m_lblMsgBig2.BlinkDynamicsValue = false;
            this.m_lblMsgBig2.Bold = true;
            brushdynamicsconvertercf2.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Green, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval4.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(28)))), ((int)(((byte)(36))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval5.End = 1D;
            brushcfinterval5.Start = 1D;
            brushcfinterval5.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Green, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval6.End = 2D;
            brushcfinterval6.Start = 2D;
            brushcfinterval6.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(194)))), ((int)(((byte)(14))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval4);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval5);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval6);
            this.m_lblMsgBig2.EnabledDynamicsValue = true;
            this.m_lblMsgBig2.FontFamily = "Arial";
            this.m_lblMsgBig2.FontSizePixels = 16;
            this.m_lblMsgBig2.Height = 42;
            this.m_lblMsgBig2.Left = 89;
            this.m_lblMsgBig2.Name = "m_lblMsgBig2";
            this.m_lblMsgBig2.ScreenOwnerName = "DiagScreen";
            this.m_lblMsgBig2.TextVerticalAlignment = "Center";
            this.m_lblMsgBig2.Top = 116;
            this.m_lblMsgBig2.VisibleDynamicsValue = true;
            this.m_lblMsgBig2.Width = 260;
            this.m_lblMsgBig2.WordWrap = true;
            // 
            // m_lblMsgBig3
            // 
            this.m_lblMsgBig3.AutoSize = false;
            this.m_lblMsgBig3.BlinkDynamicsValue = false;
            this.m_lblMsgBig3.Bold = true;
            brushdynamicsconvertercf3.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Green, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval7.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(28)))), ((int)(((byte)(36))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval8.End = 1D;
            brushcfinterval8.Start = 1D;
            brushcfinterval8.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Green, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval9.End = 2D;
            brushcfinterval9.Start = 2D;
            brushcfinterval9.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(194)))), ((int)(((byte)(14))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf3.BrushIntervalMapper.Intervals.Add(brushcfinterval7);
            brushdynamicsconvertercf3.BrushIntervalMapper.Intervals.Add(brushcfinterval8);
            brushdynamicsconvertercf3.BrushIntervalMapper.Intervals.Add(brushcfinterval9);
            this.m_lblMsgBig3.EnabledDynamicsValue = true;
            this.m_lblMsgBig3.FontFamily = "Arial";
            this.m_lblMsgBig3.FontSizePixels = 16;
            this.m_lblMsgBig3.Height = 46;
            this.m_lblMsgBig3.Left = 90;
            this.m_lblMsgBig3.Name = "m_lblMsgBig3";
            this.m_lblMsgBig3.ScreenOwnerName = "DiagScreen";
            this.m_lblMsgBig3.TextVerticalAlignment = "Center";
            this.m_lblMsgBig3.Top = 164;
            this.m_lblMsgBig3.VisibleDynamicsValue = true;
            this.m_lblMsgBig3.Width = 260;
            this.m_lblMsgBig3.WordWrap = true;
            // 
            // m_LoadGif2
            // 
            this.m_LoadGif2.BlinkDynamicsValue = false;
            this.m_LoadGif2.EnabledDynamicsValue = true;
            this.m_LoadGif2.Height = 36;
            this.m_LoadGif2.IsAnimationEnabled = true;
            this.m_LoadGif2.Left = 32;
            this.m_LoadGif2.Name = "m_LoadGif2";
            this.m_LoadGif2.ScreenOwnerName = "DiagScreen";
            this.m_LoadGif2.Stretch = true;
            this.m_LoadGif2.SymbolName = "ajax-loader (1)";
            this.m_LoadGif2.Top = 120;
            this.m_LoadGif2.VisibleDynamicsValue = true;
            this.m_LoadGif2.Width = 36;
            // 
            // m_LoadGif3
            // 
            this.m_LoadGif3.BlinkDynamicsValue = false;
            this.m_LoadGif3.EnabledDynamicsValue = true;
            this.m_LoadGif3.Height = 36;
            this.m_LoadGif3.IsAnimationEnabled = true;
            this.m_LoadGif3.Left = 32;
            this.m_LoadGif3.Name = "m_LoadGif3";
            this.m_LoadGif3.ScreenOwnerName = "DiagScreen";
            this.m_LoadGif3.Stretch = true;
            this.m_LoadGif3.SymbolName = "ajax-loader (1)";
            this.m_LoadGif3.Top = 168;
            this.m_LoadGif3.VisibleDynamicsValue = true;
            this.m_LoadGif3.Width = 36;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric.DisplayFormat = Neo.ApplicationFramework.Interfaces.AnalogNumericDisplayFormat.String;
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 12;
            this.m_AnalogNumeric.Height = 19;
            this.m_AnalogNumeric.Left = 194;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.ScreenOwnerName = "DiagScreen";
            this.m_AnalogNumeric.Top = 17;
            this.m_AnalogNumeric.VisibleDynamicsValue = true;
            this.m_AnalogNumeric.Width = 270;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(480, 272);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "DiagScreen";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_DiagScreen = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_DiagScreen) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            this.Controls.Add(this.m_pbDiag3);
            this.Controls.Add(this.m_pbDiag2);
            this.Controls.Add(this.m_pbDiag1);
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Rectangle1);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Button11);
            this.DrawingPrimitives.Add(this.m_lblMsgSmall1);
            this.DrawingPrimitives.Add(this.m_lblMsgSmall2);
            this.DrawingPrimitives.Add(this.m_lblMsgSmall3);
            this.DrawingPrimitives.Add(this.m_btnDetail1);
            this.DrawingPrimitives.Add(this.m_btnDetail2);
            this.DrawingPrimitives.Add(this.m_btnDetail3);
            this.DrawingPrimitives.Add(this.m_Line);
            this.DrawingPrimitives.Add(this.m_Line1);
            this.DrawingPrimitives.Add(this.m_Text4);
            this.DrawingPrimitives.Add(this.m_Line2);
            this.DrawingPrimitives.Add(this.m_Line3);
            this.DrawingPrimitives.Add(this.m_Line4);
            this.DrawingPrimitives.Add(this.m_Text5);
            this.DrawingPrimitives.Add(this.m_Text6);
            this.DrawingPrimitives.Add(this.m_btnSave);
            this.DrawingPrimitives.Add(this.m_LoadGif1);
            this.DrawingPrimitives.Add(this.m_picDiag1);
            this.DrawingPrimitives.Add(this.m_picDiag2);
            this.DrawingPrimitives.Add(this.m_picDiag3);
            this.DrawingPrimitives.Add(this.m_lblMsgBig1);
            this.DrawingPrimitives.Add(this.m_lblMsgBig2);
            this.DrawingPrimitives.Add(this.m_lblMsgBig3);
            this.DrawingPrimitives.Add(this.m_LoadGif2);
            this.DrawingPrimitives.Add(this.m_LoadGif3);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsgSmall1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsgSmall2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsgSmall3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnDetail1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnDetail2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnDetail3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnSave)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_LoadGif1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_picDiag1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_picDiag2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_picDiag3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsgBig1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsgBig2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_lblMsgBig3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_LoadGif2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_LoadGif3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
        }
        
        private void DiagScreen_Action_Opened(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("DiagScreen", "Opened", "Set Analog", "Tags.CurrentScreen", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.CurrentScreen.SetAnalog(12);
        }
        
        private void m_Button11_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button11", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button11", "Click", "Show Screen", "SettingScreen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.SettingScreen.Show();
        }
        
        private void m_btnDetail1_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnDetail1", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnDetail1", "Click", "Show Screen", "DiagReportFlow", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.DiagReportFlow.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnDetail1", "Click", "Set Analog", "Tags.SettingSel", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.SettingSel.SetAnalog(1);
        }
        
        private void m_btnDetail2_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnDetail2", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnDetail2", "Click", "Show Screen", "DiagReportPress", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.DiagReportPress.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnDetail2", "Click", "Set Analog", "Tags.SettingSel", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.SettingSel.SetAnalog(1);
        }
        
        private void m_btnDetail3_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnDetail3", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnDetail3", "Click", "Show Screen", "DiagReportSolenoid", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.DiagReportSolenoid.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnDetail3", "Click", "Set Analog", "Tags.SettingSel", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.SettingSel.SetAnalog(1);
        }
        
        private void m_btnSave_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnSave", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(DiagScreen));
            this.m_Text.Text = resources.GetText("DiagScreen.Text.Text", "DIAGNOSTICS");
            this.m_Button11.Text = resources.GetText("DiagScreen.Button11.Text", "BACK");
            this.m_lblMsgSmall1.Text = resources.GetText("DiagScreen.lblMsgSmall1.Text", "Checking Flow Meters...");
            this.m_lblMsgSmall2.Text = resources.GetText("DiagScreen.lblMsgSmall2.Text", "Checking Pressure Sensors...");
            this.m_lblMsgSmall3.Text = resources.GetText("DiagScreen.lblMsgSmall3.Text", "Checking Solenoid Valves...");
            this.m_btnDetail1.Text = resources.GetText("DiagScreen.btnDetail1.Text", "Detail");
            this.m_btnDetail2.Text = resources.GetText("DiagScreen.btnDetail2.Text", "Detail");
            this.m_btnDetail3.Text = resources.GetText("DiagScreen.btnDetail3.Text", "Detail");
            this.m_Text4.Text = resources.GetText("DiagScreen.Text4.Text", "Status");
            this.m_Text5.Text = resources.GetText("DiagScreen.Text5.Text", "Current Progress");
            this.m_Text6.Text = resources.GetText("DiagScreen.Text6.Text", "Click for detail");
            this.m_btnSave.Text = resources.GetText("DiagScreen.btnSave.Text", "Save Report To USB");
            this.m_lblMsgBig1.Text = resources.GetText("DiagScreen.lblMsgBig1.Text", "Flow Meters have 123 warnings!");
            this.m_lblMsgBig2.Text = resources.GetText("DiagScreen.lblMsgBig2.Text", "Inlet/Test Pressure Sensors ");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_DiagScreen) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Foreground", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagPic1"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf1);
            this.m_lblMsgBig1.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagMsg7"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_lblMsgBig1.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagMsg8"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_lblMsgBig2.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("stage1", 1));
            this.m_lblMsgBig1.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("stage2", 1));
            this.m_picDiag2.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagPic2"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_picDiag2.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 5));
            this.m_picDiag3.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagPic3"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_picDiag3.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 2));
            this.m_LoadGif2.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding10 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 5));
            this.m_lblMsgBig3.DataBindings.Add(dynamicBinding10);
            this.m_DynamicBindings.Add(dynamicBinding10);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding11 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.debugstring2"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding11);
            this.m_DynamicBindings.Add(dynamicBinding11);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding12 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 4));
            this.m_LoadGif3.DataBindings.Add(dynamicBinding12);
            this.m_DynamicBindings.Add(dynamicBinding12);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding13 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("stage2", 1));
            this.m_lblMsgBig2.DataBindings.Add(dynamicBinding13);
            this.m_DynamicBindings.Add(dynamicBinding13);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding14 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Foreground", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagPic2"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf2);
            this.m_lblMsgBig2.DataBindings.Add(dynamicBinding14);
            this.m_DynamicBindings.Add(dynamicBinding14);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding15 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Foreground", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagPic3"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf3);
            this.m_lblMsgBig3.DataBindings.Add(dynamicBinding15);
            this.m_DynamicBindings.Add(dynamicBinding15);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding16 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagMsg9"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_lblMsgBig3.DataBindings.Add(dynamicBinding16);
            this.m_DynamicBindings.Add(dynamicBinding16);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding17 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 4));
            this.m_pbDiag3.DataBindings.Add(dynamicBinding17);
            this.m_DynamicBindings.Add(dynamicBinding17);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding18 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagProgressBar3"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_pbDiag3.DataBindings.Add(dynamicBinding18);
            this.m_DynamicBindings.Add(dynamicBinding18);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding19 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 2));
            this.m_lblMsgSmall2.DataBindings.Add(dynamicBinding19);
            this.m_DynamicBindings.Add(dynamicBinding19);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding20 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueZero);
            this.m_lblMsgSmall1.DataBindings.Add(dynamicBinding20);
            this.m_DynamicBindings.Add(dynamicBinding20);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding21 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueZero);
            this.m_pbDiag1.DataBindings.Add(dynamicBinding21);
            this.m_DynamicBindings.Add(dynamicBinding21);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding22 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagProgressBar1"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_pbDiag1.DataBindings.Add(dynamicBinding22);
            this.m_DynamicBindings.Add(dynamicBinding22);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding23 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 2));
            this.m_pbDiag2.DataBindings.Add(dynamicBinding23);
            this.m_DynamicBindings.Add(dynamicBinding23);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding24 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagProgressBar2"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_pbDiag2.DataBindings.Add(dynamicBinding24);
            this.m_DynamicBindings.Add(dynamicBinding24);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding25 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueZero);
            this.m_LoadGif1.DataBindings.Add(dynamicBinding25);
            this.m_DynamicBindings.Add(dynamicBinding25);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding26 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 5));
            this.m_btnSave.DataBindings.Add(dynamicBinding26);
            this.m_DynamicBindings.Add(dynamicBinding26);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding27 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("stage1", 1));
            this.m_picDiag1.DataBindings.Add(dynamicBinding27);
            this.m_DynamicBindings.Add(dynamicBinding27);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding28 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagPic1"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_picDiag1.DataBindings.Add(dynamicBinding28);
            this.m_DynamicBindings.Add(dynamicBinding28);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding29 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 5));
            this.m_btnDetail1.DataBindings.Add(dynamicBinding29);
            this.m_DynamicBindings.Add(dynamicBinding29);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding30 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 4));
            this.m_lblMsgSmall3.DataBindings.Add(dynamicBinding30);
            this.m_DynamicBindings.Add(dynamicBinding30);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding31 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 5));
            this.m_btnDetail3.DataBindings.Add(dynamicBinding31);
            this.m_DynamicBindings.Add(dynamicBinding31);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding32 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.DiagStage"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, new Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF("", 5));
            this.m_btnDetail2.DataBindings.Add(dynamicBinding32);
            this.m_DynamicBindings.Add(dynamicBinding32);
        }
    }
}
