//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class FilterSettingLow : Neo.ApplicationFramework.Tools.Recipe.Recipe
	{
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Filter_Low_UpperLimit;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_Filter_Low_Response;
		
		public FilterSettingLow()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Filter_Low_UpperLimit
		{
			get
			{
				return this.m_Filter_Low_UpperLimit;
			}
			set
			{
				this.m_Filter_Low_UpperLimit = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem Filter_Low_Response
		{
			get
			{
				return this.m_Filter_Low_Response;
			}
			set
			{
				this.m_Filter_Low_Response = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public override void ConnectDataBindings()
		{
			base.ConnectDataBindings();
		}
		
		private void InitializeObjectCreations()
		{
			this.Filter_Low_UpperLimit = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.Filter_Low_Response = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.DataVersion = ((long)(346));
			this.FieldNames.Add("Current");
			this.FieldNames.Add("Default");
			this.Guid = new System.Guid("fad13a79-1385-408c-9082-f48638e28033");
			this.Filter_Low_UpperLimit.ColumnName = "Filter_Low_UpperLimit";
			this.Filter_Low_UpperLimit.DataConnection = "Tags.FilterUpperLimitLow";
			this.Filter_Low_UpperLimit.Name = "Filter_Low_UpperLimit";
			this.Filter_Low_UpperLimit.VisualSortOrder = 99;
			this.Filter_Low_Response.ColumnName = "Filter_Low_Response";
			this.Filter_Low_Response.DataConnection = "Tags.FilterResponseLow";
			this.Filter_Low_Response.Name = "Filter_Low_Response";
			this.Filter_Low_Response.VisualSortOrder = 100;
			this.RecipeItems.Add(this.Filter_Low_UpperLimit);
			this.RecipeItems.Add(this.Filter_Low_Response);
			this.SchemaVersion = ((long)(591));
			this.TableName = "FilterSettingLow";
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(FilterSettingLow));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
