//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class popPasscode : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPass7;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPass8;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPass9;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPassDel;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPass4;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPass5;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPass6;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPass1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPass2;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPass3;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPass0;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPassEnter;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnPassClose;
        
        private bool m_Initialized_popPasscode;
        
        public popPasscode() {
            this.InitializeComponent();
            this.btnPass7.Click += new System.EventHandler(this.btnPass7_Click);
            this.btnPass8.Click += new System.EventHandler(this.btnPass8_Click);
            this.btnPass9.Click += new System.EventHandler(this.btnPass9_Click);
            this.btnPassDel.Click += new System.EventHandler(this.btnPassDel_Click);
            this.btnPass4.Click += new System.EventHandler(this.btnPass4_Click);
            this.btnPass5.Click += new System.EventHandler(this.btnPass5_Click);
            this.btnPass6.Click += new System.EventHandler(this.btnPass6_Click);
            this.btnPass1.Click += new System.EventHandler(this.btnPass1_Click);
            this.btnPass2.Click += new System.EventHandler(this.btnPass2_Click);
            this.btnPass3.Click += new System.EventHandler(this.btnPass3_Click);
            this.btnPass0.Click += new System.EventHandler(this.btnPass0_Click);
            this.btnPassEnter.Click += new System.EventHandler(this.btnPassEnter_Click);
            this.Adapter.Opened += new System.EventHandler(this.popPasscode_Opened);
            this.Opened += new System.EventHandler(this.popPasscode_Action_Opened);
            this.m_btnPassClose.Click += new System.EventHandler(this.m_btnPassClose_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPass7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPass7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPass8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPass8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPass9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPass9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPassDel {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPassDel);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPass4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPass4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPass5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPass5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPass6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPass6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPass1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPass1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPass2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPass2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPass3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPass3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPass0 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPass0);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPassEnter {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPassEnter);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnPassClose {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnPassClose);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper9 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper10 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper11 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper12 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper13 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_btnPass7 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_btnPass8 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPass9 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPassDel = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPass4 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPass5 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPass6 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPass1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPass2 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPass3 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPass0 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPassEnter = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnPassClose = new Neo.ApplicationFramework.Controls.Controls.Button();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPassDel)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass0)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPassEnter)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPassClose)).BeginInit();
            this.SuspendLayout();
            // 
            // popPasscode
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_btnPass7
            // 
            this.m_btnPass7.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass7.BlinkDynamicsValue = false;
            this.m_btnPass7.Bold = true;
            this.m_btnPass7.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass7.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnPass7.EnabledDynamicsValue = true;
            this.m_btnPass7.FontSizePixels = 24;
            this.m_btnPass7.ForceTransparency = true;
            this.m_btnPass7.Height = 49;
            this.m_btnPass7.IndicatorMargin = null;
            this.m_btnPass7.Left = 11;
            this.m_btnPass7.Name = "m_btnPass7";
            this.m_btnPass7.RequiresTransparency = true;
            this.m_btnPass7.ScreenOwnerName = "popPasscode";
            this.m_btnPass7.StyleName = "Eclipse";
            this.m_btnPass7.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_btnPass7.TextHeight = 29;
            this.m_btnPass7.TextValue = 0D;
            this.m_btnPass7.TextWidth = 60;
            this.m_btnPass7.Top = 37;
            this.m_btnPass7.Value = 0D;
            this.m_btnPass7.VisibleDynamicsValue = true;
            this.m_btnPass7.VisualPropertiesHashCode = 1360642202;
            this.m_btnPass7.Width = 66;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric.DisplayFormat = Neo.ApplicationFramework.Interfaces.AnalogNumericDisplayFormat.String;
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 18;
            this.m_AnalogNumeric.Height = 29;
            this.m_AnalogNumeric.Left = 11;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.ScreenOwnerName = "popPasscode";
            this.m_AnalogNumeric.Top = 4;
            this.m_AnalogNumeric.VisibleDynamicsValue = true;
            this.m_AnalogNumeric.Width = 263;
            // 
            // m_btnPass8
            // 
            this.m_btnPass8.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass8.BlinkDynamicsValue = false;
            this.m_btnPass8.Bold = true;
            this.m_btnPass8.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass8.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnPass8.EnabledDynamicsValue = true;
            this.m_btnPass8.FontSizePixels = 24;
            this.m_btnPass8.ForceTransparency = true;
            this.m_btnPass8.Height = 49;
            this.m_btnPass8.IndicatorMargin = null;
            this.m_btnPass8.Left = 76;
            this.m_btnPass8.Name = "m_btnPass8";
            this.m_btnPass8.RequiresTransparency = true;
            this.m_btnPass8.ScreenOwnerName = "popPasscode";
            this.m_btnPass8.StyleName = "Eclipse";
            this.m_btnPass8.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_btnPass8.TextHeight = 29;
            this.m_btnPass8.TextValue = 0D;
            this.m_btnPass8.TextWidth = 60;
            this.m_btnPass8.Top = 37;
            this.m_btnPass8.Value = 0D;
            this.m_btnPass8.VisibleDynamicsValue = true;
            this.m_btnPass8.VisualPropertiesHashCode = 1360642202;
            this.m_btnPass8.Width = 66;
            // 
            // m_btnPass9
            // 
            this.m_btnPass9.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass9.BlinkDynamicsValue = false;
            this.m_btnPass9.Bold = true;
            this.m_btnPass9.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass9.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnPass9.EnabledDynamicsValue = true;
            this.m_btnPass9.FontSizePixels = 24;
            this.m_btnPass9.ForceTransparency = true;
            this.m_btnPass9.Height = 49;
            this.m_btnPass9.IndicatorMargin = null;
            this.m_btnPass9.Left = 142;
            this.m_btnPass9.Name = "m_btnPass9";
            this.m_btnPass9.RequiresTransparency = true;
            this.m_btnPass9.ScreenOwnerName = "popPasscode";
            this.m_btnPass9.StyleName = "Eclipse";
            this.m_btnPass9.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_btnPass9.TextHeight = 29;
            this.m_btnPass9.TextValue = 0D;
            this.m_btnPass9.TextWidth = 60;
            this.m_btnPass9.Top = 37;
            this.m_btnPass9.Value = 0D;
            this.m_btnPass9.VisibleDynamicsValue = true;
            this.m_btnPass9.VisualPropertiesHashCode = 1360642202;
            this.m_btnPass9.Width = 66;
            // 
            // m_btnPassDel
            // 
            this.m_btnPassDel.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPassDel.BlinkDynamicsValue = false;
            this.m_btnPassDel.Bold = true;
            this.m_btnPassDel.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPassDel.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnPassDel.EnabledDynamicsValue = true;
            this.m_btnPassDel.FontSizePixels = 24;
            this.m_btnPassDel.ForceTransparency = true;
            this.m_btnPassDel.Height = 49;
            this.m_btnPassDel.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 10D, 1D, 10D);
            this.m_btnPassDel.IndicatorMargin = null;
            this.m_btnPassDel.Left = 208;
            this.m_btnPassDel.Name = "m_btnPassDel";
            this.m_btnPassDel.RequiresTransparency = true;
            this.m_btnPassDel.ScreenOwnerName = "popPasscode";
            this.m_btnPassDel.StyleName = "Eclipse";
            this.m_btnPassDel.SymbolHeight = 27;
            this.m_btnPassDel.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_btnPassDel.SymbolName = "path5894";
            this.m_btnPassDel.SymbolWidth = 46;
            this.m_btnPassDel.TextHeight = 29;
            this.m_btnPassDel.TextValue = 0D;
            this.m_btnPassDel.TextWidth = 60;
            this.m_btnPassDel.Top = 37;
            this.m_btnPassDel.Value = 0D;
            this.m_btnPassDel.VisibleDynamicsValue = true;
            this.m_btnPassDel.VisualPropertiesHashCode = -1572245879;
            this.m_btnPassDel.Width = 66;
            // 
            // m_btnPass4
            // 
            this.m_btnPass4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass4.BlinkDynamicsValue = false;
            this.m_btnPass4.Bold = true;
            this.m_btnPass4.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnPass4.EnabledDynamicsValue = true;
            this.m_btnPass4.FontSizePixels = 24;
            this.m_btnPass4.ForceTransparency = true;
            this.m_btnPass4.Height = 49;
            this.m_btnPass4.IndicatorMargin = null;
            this.m_btnPass4.Left = 11;
            this.m_btnPass4.Name = "m_btnPass4";
            this.m_btnPass4.RequiresTransparency = true;
            this.m_btnPass4.ScreenOwnerName = "popPasscode";
            this.m_btnPass4.StyleName = "Eclipse";
            this.m_btnPass4.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_btnPass4.TextHeight = 29;
            this.m_btnPass4.TextValue = 0D;
            this.m_btnPass4.TextWidth = 60;
            this.m_btnPass4.Top = 86;
            this.m_btnPass4.Value = 0D;
            this.m_btnPass4.VisibleDynamicsValue = true;
            this.m_btnPass4.VisualPropertiesHashCode = 1360642202;
            this.m_btnPass4.Width = 66;
            // 
            // m_btnPass5
            // 
            this.m_btnPass5.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass5.BlinkDynamicsValue = false;
            this.m_btnPass5.Bold = true;
            this.m_btnPass5.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass5.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnPass5.EnabledDynamicsValue = true;
            this.m_btnPass5.FontSizePixels = 24;
            this.m_btnPass5.ForceTransparency = true;
            this.m_btnPass5.Height = 49;
            this.m_btnPass5.IndicatorMargin = null;
            this.m_btnPass5.Left = 76;
            this.m_btnPass5.Name = "m_btnPass5";
            this.m_btnPass5.RequiresTransparency = true;
            this.m_btnPass5.ScreenOwnerName = "popPasscode";
            this.m_btnPass5.StyleName = "Eclipse";
            this.m_btnPass5.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_btnPass5.TextHeight = 29;
            this.m_btnPass5.TextValue = 0D;
            this.m_btnPass5.TextWidth = 60;
            this.m_btnPass5.Top = 86;
            this.m_btnPass5.Value = 0D;
            this.m_btnPass5.VisibleDynamicsValue = true;
            this.m_btnPass5.VisualPropertiesHashCode = 1360642202;
            this.m_btnPass5.Width = 66;
            // 
            // m_btnPass6
            // 
            this.m_btnPass6.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass6.BlinkDynamicsValue = false;
            this.m_btnPass6.Bold = true;
            this.m_btnPass6.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass6.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnPass6.EnabledDynamicsValue = true;
            this.m_btnPass6.FontSizePixels = 24;
            this.m_btnPass6.ForceTransparency = true;
            this.m_btnPass6.Height = 49;
            this.m_btnPass6.IndicatorMargin = null;
            this.m_btnPass6.Left = 142;
            this.m_btnPass6.Name = "m_btnPass6";
            this.m_btnPass6.RequiresTransparency = true;
            this.m_btnPass6.ScreenOwnerName = "popPasscode";
            this.m_btnPass6.StyleName = "Eclipse";
            this.m_btnPass6.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_btnPass6.TextHeight = 29;
            this.m_btnPass6.TextValue = 0D;
            this.m_btnPass6.TextWidth = 60;
            this.m_btnPass6.Top = 86;
            this.m_btnPass6.Value = 0D;
            this.m_btnPass6.VisibleDynamicsValue = true;
            this.m_btnPass6.VisualPropertiesHashCode = 1360642202;
            this.m_btnPass6.Width = 66;
            // 
            // m_btnPass1
            // 
            this.m_btnPass1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass1.BlinkDynamicsValue = false;
            this.m_btnPass1.Bold = true;
            this.m_btnPass1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnPass1.EnabledDynamicsValue = true;
            this.m_btnPass1.FontSizePixels = 24;
            this.m_btnPass1.ForceTransparency = true;
            this.m_btnPass1.Height = 49;
            this.m_btnPass1.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 5D, 2D, 5D);
            this.m_btnPass1.IndicatorMargin = null;
            this.m_btnPass1.Left = 11;
            this.m_btnPass1.Name = "m_btnPass1";
            this.m_btnPass1.RequiresTransparency = true;
            this.m_btnPass1.ScreenOwnerName = "popPasscode";
            this.m_btnPass1.StyleName = "Eclipse";
            this.m_btnPass1.SymbolIntervalMapper = symbolintervalmapper8;
            this.m_btnPass1.SymbolName = "";
            this.m_btnPass1.TextHeight = 29;
            this.m_btnPass1.TextValue = 0D;
            this.m_btnPass1.TextWidth = 60;
            this.m_btnPass1.Top = 135;
            this.m_btnPass1.Value = 0D;
            this.m_btnPass1.VisibleDynamicsValue = true;
            this.m_btnPass1.VisualPropertiesHashCode = 1604607797;
            this.m_btnPass1.Width = 66;
            // 
            // m_btnPass2
            // 
            this.m_btnPass2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass2.BlinkDynamicsValue = false;
            this.m_btnPass2.Bold = true;
            this.m_btnPass2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnPass2.EnabledDynamicsValue = true;
            this.m_btnPass2.FontSizePixels = 24;
            this.m_btnPass2.ForceTransparency = true;
            this.m_btnPass2.Height = 49;
            this.m_btnPass2.IndicatorMargin = null;
            this.m_btnPass2.Left = 76;
            this.m_btnPass2.Name = "m_btnPass2";
            this.m_btnPass2.RequiresTransparency = true;
            this.m_btnPass2.ScreenOwnerName = "popPasscode";
            this.m_btnPass2.StyleName = "Eclipse";
            this.m_btnPass2.SymbolIntervalMapper = symbolintervalmapper9;
            this.m_btnPass2.TextHeight = 29;
            this.m_btnPass2.TextValue = 0D;
            this.m_btnPass2.TextWidth = 60;
            this.m_btnPass2.Top = 135;
            this.m_btnPass2.Value = 0D;
            this.m_btnPass2.VisibleDynamicsValue = true;
            this.m_btnPass2.VisualPropertiesHashCode = 1360642202;
            this.m_btnPass2.Width = 66;
            // 
            // m_btnPass3
            // 
            this.m_btnPass3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass3.BlinkDynamicsValue = false;
            this.m_btnPass3.Bold = true;
            this.m_btnPass3.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass3.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnPass3.EnabledDynamicsValue = true;
            this.m_btnPass3.FontSizePixels = 24;
            this.m_btnPass3.ForceTransparency = true;
            this.m_btnPass3.Height = 49;
            this.m_btnPass3.IndicatorMargin = null;
            this.m_btnPass3.Left = 142;
            this.m_btnPass3.Name = "m_btnPass3";
            this.m_btnPass3.RequiresTransparency = true;
            this.m_btnPass3.ScreenOwnerName = "popPasscode";
            this.m_btnPass3.StyleName = "Eclipse";
            this.m_btnPass3.SymbolIntervalMapper = symbolintervalmapper10;
            this.m_btnPass3.TextHeight = 29;
            this.m_btnPass3.TextValue = 0D;
            this.m_btnPass3.TextWidth = 60;
            this.m_btnPass3.Top = 135;
            this.m_btnPass3.Value = 0D;
            this.m_btnPass3.VisibleDynamicsValue = true;
            this.m_btnPass3.VisualPropertiesHashCode = 1360642202;
            this.m_btnPass3.Width = 66;
            // 
            // m_btnPass0
            // 
            this.m_btnPass0.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass0.BlinkDynamicsValue = false;
            this.m_btnPass0.Bold = true;
            this.m_btnPass0.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPass0.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnPass0.EnabledDynamicsValue = true;
            this.m_btnPass0.FontSizePixels = 24;
            this.m_btnPass0.ForceTransparency = true;
            this.m_btnPass0.Height = 49;
            this.m_btnPass0.IndicatorMargin = null;
            this.m_btnPass0.Left = 11;
            this.m_btnPass0.Name = "m_btnPass0";
            this.m_btnPass0.RequiresTransparency = true;
            this.m_btnPass0.ScreenOwnerName = "popPasscode";
            this.m_btnPass0.StyleName = "Eclipse";
            this.m_btnPass0.SymbolIntervalMapper = symbolintervalmapper11;
            this.m_btnPass0.TextHeight = 29;
            this.m_btnPass0.TextValue = 0D;
            this.m_btnPass0.TextWidth = 60;
            this.m_btnPass0.Top = 184;
            this.m_btnPass0.Value = 0D;
            this.m_btnPass0.VisibleDynamicsValue = true;
            this.m_btnPass0.VisualPropertiesHashCode = 1360642202;
            this.m_btnPass0.Width = 66;
            // 
            // m_btnPassEnter
            // 
            this.m_btnPassEnter.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPassEnter.BlinkDynamicsValue = false;
            this.m_btnPassEnter.Bold = true;
            this.m_btnPassEnter.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPassEnter.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnPassEnter.EnabledDynamicsValue = true;
            this.m_btnPassEnter.FontSizePixels = 24;
            this.m_btnPassEnter.ForceTransparency = true;
            this.m_btnPassEnter.Height = 49;
            this.m_btnPassEnter.IndicatorMargin = null;
            this.m_btnPassEnter.Left = 76;
            this.m_btnPassEnter.Name = "m_btnPassEnter";
            this.m_btnPassEnter.RequiresTransparency = true;
            this.m_btnPassEnter.ScreenOwnerName = "popPasscode";
            this.m_btnPassEnter.StyleName = "Eclipse";
            this.m_btnPassEnter.SymbolIntervalMapper = symbolintervalmapper12;
            this.m_btnPassEnter.TextHeight = 29;
            this.m_btnPassEnter.TextValue = 0D;
            this.m_btnPassEnter.TextWidth = 89;
            this.m_btnPassEnter.Top = 184;
            this.m_btnPassEnter.Value = 0D;
            this.m_btnPassEnter.VisibleDynamicsValue = true;
            this.m_btnPassEnter.VisualPropertiesHashCode = 1159526462;
            this.m_btnPassEnter.Width = 95;
            // 
            // m_btnPassClose
            // 
            this.m_btnPassClose.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(131)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPassClose.BlinkDynamicsValue = false;
            this.m_btnPassClose.Bold = true;
            this.m_btnPassClose.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnPassClose.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_btnPassClose.EnabledDynamicsValue = true;
            this.m_btnPassClose.FontSizePixels = 24;
            this.m_btnPassClose.ForceTransparency = true;
            this.m_btnPassClose.Height = 49;
            this.m_btnPassClose.IndicatorMargin = null;
            this.m_btnPassClose.Left = 171;
            this.m_btnPassClose.Name = "m_btnPassClose";
            this.m_btnPassClose.RequiresTransparency = true;
            this.m_btnPassClose.ScreenOwnerName = "popPasscode";
            this.m_btnPassClose.StyleName = "Eclipse";
            this.m_btnPassClose.SymbolIntervalMapper = symbolintervalmapper13;
            this.m_btnPassClose.TextHeight = 29;
            this.m_btnPassClose.TextValue = 0D;
            this.m_btnPassClose.TextWidth = 97;
            this.m_btnPassClose.Top = 184;
            this.m_btnPassClose.Value = 0D;
            this.m_btnPassClose.VisibleDynamicsValue = true;
            this.m_btnPassClose.VisualPropertiesHashCode = -115852733;
            this.m_btnPassClose.Width = 103;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.ClientSize = new System.Drawing.Size(303, 235);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(87, 3);
            this.ModalScreen = true;
            this.Name = "popPasscode";
            this.PopupScreen = true;
            this.ScreenID = null;
            this.ScreenTitle = "ENTER ACCESS CODE";
            this.StyleName = "Default";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_popPasscode = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_popPasscode) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_btnPass7);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            this.DrawingPrimitives.Add(this.m_btnPass8);
            this.DrawingPrimitives.Add(this.m_btnPass9);
            this.DrawingPrimitives.Add(this.m_btnPassDel);
            this.DrawingPrimitives.Add(this.m_btnPass4);
            this.DrawingPrimitives.Add(this.m_btnPass5);
            this.DrawingPrimitives.Add(this.m_btnPass6);
            this.DrawingPrimitives.Add(this.m_btnPass1);
            this.DrawingPrimitives.Add(this.m_btnPass2);
            this.DrawingPrimitives.Add(this.m_btnPass3);
            this.DrawingPrimitives.Add(this.m_btnPass0);
            this.DrawingPrimitives.Add(this.m_btnPassEnter);
            this.DrawingPrimitives.Add(this.m_btnPassClose);
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPassDel)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPass0)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPassEnter)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnPassClose)).EndInit();
        }
        
        private void popPasscode_Action_Opened(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("popPasscode", "Opened", "Set Analog", "Tags.CurrentScreen", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.CurrentScreen.SetAnalog(24);
        }
        
        private void m_btnPassClose_Action_Click(object sender, System.EventArgs e) {
            this.LogClose("m_btnPassClose", "Click", "Close Screen", "");
            this.Close();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(popPasscode));
            this.m_btnPass7.Text = resources.GetText("popPasscode.btnPass7.Text", "7");
            this.m_btnPass8.Text = resources.GetText("popPasscode.btnPass8.Text", "8");
            this.m_btnPass9.Text = resources.GetText("popPasscode.btnPass9.Text", "9");
            this.m_btnPass4.Text = resources.GetText("popPasscode.btnPass4.Text", "4");
            this.m_btnPass5.Text = resources.GetText("popPasscode.btnPass5.Text", "5");
            this.m_btnPass6.Text = resources.GetText("popPasscode.btnPass6.Text", "6");
            this.m_btnPass1.Text = resources.GetText("popPasscode.btnPass1.Text", "1");
            this.m_btnPass2.Text = resources.GetText("popPasscode.btnPass2.Text", "2");
            this.m_btnPass3.Text = resources.GetText("popPasscode.btnPass3.Text", "3");
            this.m_btnPass0.Text = resources.GetText("popPasscode.btnPass0.Text", "0");
            this.m_btnPassEnter.Text = resources.GetText("popPasscode.btnPassEnter.Text", "ENTER");
            this.m_btnPassClose.Text = resources.GetText("popPasscode.btnPassClose.Text", "BACK");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_popPasscode) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Enter_pwd"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
        }
    }
}
