//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class QuickFillSetting : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button21;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button2;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric2;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button4;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private bool m_Initialized_QuickFillSetting;
        
        public QuickFillSetting() {
            this.InitializeComponent();
            this.Button21.Click += new System.EventHandler(this.Button21_Click);
            this.Button.Click += new System.EventHandler(this.Button_Click);
            this.Button1.Click += new System.EventHandler(this.Button1_Click);
            this.Button2.Click += new System.EventHandler(this.Button2_Click);
            this.Button3.Click += new System.EventHandler(this.Button3_Click);
            this.Button4.Click += new System.EventHandler(this.Button4_Click);
            this.Button5.Click += new System.EventHandler(this.Button5_Click);
            this.Opened += new System.EventHandler(this.QuickFillSetting_Action_Opened);
            this.m_Button21.Click += new System.EventHandler(this.m_Button21_Action_Click);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.m_Button1.Click += new System.EventHandler(this.m_Button1_Action_Click);
            this.m_Button2.Click += new System.EventHandler(this.m_Button2_Action_Click);
            this.m_Button3.Click += new System.EventHandler(this.m_Button3_Action_Click);
            this.m_Button4.Click += new System.EventHandler(this.m_Button4_Action_Click);
            this.m_Button5.Click += new System.EventHandler(this.m_Button5_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button21 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button21);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button21 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_AnalogNumeric1 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Button2 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button3 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric2 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Button4 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button5 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button21)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            this.SuspendLayout();
            // 
            // QuickFillSetting
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(187)))), ((int)(((byte)(187)))), ((int)(((byte)(187))))), System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Text1
            // 
            this.m_Text1.AutoSize = false;
            this.m_Text1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.Bold = true;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontFamily = "Arial";
            this.m_Text1.FontSizePixels = 20;
            this.m_Text1.Height = 30;
            this.m_Text1.Left = 0;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.ScreenOwnerName = "QuickFillSetting";
            this.m_Text1.TextHorizontalAlignment = "Center";
            this.m_Text1.TextVerticalAlignment = "Center";
            this.m_Text1.Top = 0;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 480;
            // 
            // m_Button21
            // 
            this.m_Button21.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button21.BlinkDynamicsValue = false;
            this.m_Button21.Bold = true;
            this.m_Button21.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button21.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button21.EnabledDynamicsValue = true;
            this.m_Button21.FontFamily = "Arial";
            this.m_Button21.FontSizePixels = 16;
            this.m_Button21.ForceTransparency = true;
            this.m_Button21.Height = 47;
            this.m_Button21.IndicatorMargin = null;
            this.m_Button21.Left = 8;
            this.m_Button21.Name = "m_Button21";
            this.m_Button21.RequiresTransparency = true;
            this.m_Button21.ScreenOwnerName = "QuickFillSetting";
            this.m_Button21.StyleName = "Chrome";
            this.m_Button21.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button21.SymbolName = "";
            this.m_Button21.TextHeight = 19;
            this.m_Button21.TextValue = 0D;
            this.m_Button21.TextWidth = 101;
            this.m_Button21.Top = 219;
            this.m_Button21.Value = 0D;
            this.m_Button21.VisibleDynamicsValue = true;
            this.m_Button21.VisualPropertiesHashCode = 2126007191;
            this.m_Button21.Width = 107;
            // 
            // m_AnalogNumeric1
            // 
            this.m_AnalogNumeric1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric1.BlinkDynamicsValue = false;
            this.m_AnalogNumeric1.Bold = true;
            this.m_AnalogNumeric1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric1.DisplayFormat = Neo.ApplicationFramework.Interfaces.AnalogNumericDisplayFormat.Decimal;
            this.m_AnalogNumeric1.EnabledDynamicsValue = true;
            this.m_AnalogNumeric1.FontSizePixels = 20;
            this.m_AnalogNumeric1.Height = 50;
            this.m_AnalogNumeric1.Left = 207;
            this.m_AnalogNumeric1.Name = "m_AnalogNumeric1";
            this.m_AnalogNumeric1.NumberOfDecimals = 0;
            this.m_AnalogNumeric1.ReadOnly = true;
            this.m_AnalogNumeric1.ScreenOwnerName = "QuickFillSetting";
            this.m_AnalogNumeric1.Top = 60;
            this.m_AnalogNumeric1.VisibleDynamicsValue = true;
            this.m_AnalogNumeric1.Width = 76;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 9;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button.Height = 50;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 282;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "QuickFillSetting";
            this.m_Button.StyleName = "Glossy";
            this.m_Button.SymbolHeight = 44;
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button.SymbolName = "path2985";
            this.m_Button.SymbolWidth = 38;
            this.m_Button.TextHeight = 11;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 52;
            this.m_Button.Top = 60;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = 290860501;
            this.m_Button.Width = 58;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontSizePixels = 9;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button1.Height = 50;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 152;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "QuickFillSetting";
            this.m_Button1.StyleName = "Glossy";
            this.m_Button1.SymbolHeight = 44;
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button1.SymbolName = "path29851";
            this.m_Button1.SymbolWidth = 38;
            this.m_Button1.TextHeight = 11;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 50;
            this.m_Button1.Top = 60;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = 2129827492;
            this.m_Button1.Width = 56;
            // 
            // m_Text
            // 
            this.m_Text.AutoSize = false;
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 18;
            this.m_Text.Height = 31;
            this.m_Text.Left = 104;
            this.m_Text.Name = "m_Text";
            this.m_Text.ScreenOwnerName = "QuickFillSetting";
            this.m_Text.Top = 30;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 300;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.Bold = true;
            this.m_AnalogNumeric.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 20;
            this.m_AnalogNumeric.Height = 50;
            this.m_AnalogNumeric.Left = 207;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.NumberOfDecimals = 0;
            this.m_AnalogNumeric.ReadOnly = true;
            this.m_AnalogNumeric.ScreenOwnerName = "QuickFillSetting";
            this.m_AnalogNumeric.Top = 216;
            this.m_AnalogNumeric.VisibleDynamicsValue = true;
            this.m_AnalogNumeric.Width = 76;
            // 
            // m_Button2
            // 
            this.m_Button2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BlinkDynamicsValue = false;
            this.m_Button2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button2.EnabledDynamicsValue = true;
            this.m_Button2.FontSizePixels = 9;
            this.m_Button2.ForceTransparency = true;
            this.m_Button2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button2.Height = 49;
            this.m_Button2.IndicatorMargin = null;
            this.m_Button2.Left = 282;
            this.m_Button2.Name = "m_Button2";
            this.m_Button2.RequiresTransparency = true;
            this.m_Button2.ScreenOwnerName = "QuickFillSetting";
            this.m_Button2.StyleName = "Glossy";
            this.m_Button2.SymbolHeight = 43;
            this.m_Button2.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button2.SymbolName = "path2985";
            this.m_Button2.SymbolWidth = 37;
            this.m_Button2.TextHeight = 11;
            this.m_Button2.TextValue = 0D;
            this.m_Button2.TextWidth = 52;
            this.m_Button2.Top = 216;
            this.m_Button2.Value = 0D;
            this.m_Button2.VisibleDynamicsValue = true;
            this.m_Button2.VisualPropertiesHashCode = -1901876982;
            this.m_Button2.Width = 58;
            // 
            // m_Button3
            // 
            this.m_Button3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.BlinkDynamicsValue = false;
            this.m_Button3.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button3.EnabledDynamicsValue = true;
            this.m_Button3.FontSizePixels = 9;
            this.m_Button3.ForceTransparency = true;
            this.m_Button3.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button3.Height = 50;
            this.m_Button3.IndicatorMargin = null;
            this.m_Button3.Left = 152;
            this.m_Button3.Name = "m_Button3";
            this.m_Button3.RequiresTransparency = true;
            this.m_Button3.ScreenOwnerName = "QuickFillSetting";
            this.m_Button3.StyleName = "Glossy";
            this.m_Button3.SymbolHeight = 44;
            this.m_Button3.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_Button3.SymbolName = "path29851";
            this.m_Button3.SymbolWidth = 38;
            this.m_Button3.TextHeight = 11;
            this.m_Button3.TextValue = 0D;
            this.m_Button3.TextWidth = 50;
            this.m_Button3.Top = 216;
            this.m_Button3.Value = 0D;
            this.m_Button3.VisibleDynamicsValue = true;
            this.m_Button3.VisualPropertiesHashCode = 2129827492;
            this.m_Button3.Width = 56;
            // 
            // m_Text2
            // 
            this.m_Text2.AutoSize = false;
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 18;
            this.m_Text2.Height = 33;
            this.m_Text2.Left = 113;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.ScreenOwnerName = "QuickFillSetting";
            this.m_Text2.TextHorizontalAlignment = "Center";
            this.m_Text2.TextVerticalAlignment = "Center";
            this.m_Text2.Top = 185;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 274;
            // 
            // m_AnalogNumeric2
            // 
            this.m_AnalogNumeric2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric2.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric2.BlinkDynamicsValue = false;
            this.m_AnalogNumeric2.Bold = true;
            this.m_AnalogNumeric2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric2.DisplayFormat = Neo.ApplicationFramework.Interfaces.AnalogNumericDisplayFormat.Decimal;
            this.m_AnalogNumeric2.EnabledDynamicsValue = true;
            this.m_AnalogNumeric2.FontSizePixels = 20;
            this.m_AnalogNumeric2.Height = 50;
            this.m_AnalogNumeric2.Left = 207;
            this.m_AnalogNumeric2.Name = "m_AnalogNumeric2";
            this.m_AnalogNumeric2.NumberOfDecimals = 0;
            this.m_AnalogNumeric2.ReadOnly = true;
            this.m_AnalogNumeric2.ScreenOwnerName = "QuickFillSetting";
            this.m_AnalogNumeric2.Top = 136;
            this.m_AnalogNumeric2.VisibleDynamicsValue = true;
            this.m_AnalogNumeric2.Width = 76;
            // 
            // m_Button4
            // 
            this.m_Button4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BlinkDynamicsValue = false;
            this.m_Button4.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button4.EnabledDynamicsValue = true;
            this.m_Button4.FontSizePixels = 9;
            this.m_Button4.ForceTransparency = true;
            this.m_Button4.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button4.Height = 50;
            this.m_Button4.IndicatorMargin = null;
            this.m_Button4.Left = 282;
            this.m_Button4.Name = "m_Button4";
            this.m_Button4.RequiresTransparency = true;
            this.m_Button4.ScreenOwnerName = "QuickFillSetting";
            this.m_Button4.StyleName = "Glossy";
            this.m_Button4.SymbolHeight = 44;
            this.m_Button4.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_Button4.SymbolName = "path2985";
            this.m_Button4.SymbolWidth = 38;
            this.m_Button4.TextHeight = 11;
            this.m_Button4.TextValue = 0D;
            this.m_Button4.TextWidth = 52;
            this.m_Button4.Top = 136;
            this.m_Button4.Value = 0D;
            this.m_Button4.VisibleDynamicsValue = true;
            this.m_Button4.VisualPropertiesHashCode = 290860501;
            this.m_Button4.Width = 58;
            // 
            // m_Button5
            // 
            this.m_Button5.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(187)))), ((int)(((byte)(229))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BlinkDynamicsValue = false;
            this.m_Button5.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_Button5.EnabledDynamicsValue = true;
            this.m_Button5.FontSizePixels = 9;
            this.m_Button5.ForceTransparency = true;
            this.m_Button5.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Button5.Height = 50;
            this.m_Button5.IndicatorMargin = null;
            this.m_Button5.Left = 152;
            this.m_Button5.Name = "m_Button5";
            this.m_Button5.RequiresTransparency = true;
            this.m_Button5.ScreenOwnerName = "QuickFillSetting";
            this.m_Button5.StyleName = "Glossy";
            this.m_Button5.SymbolHeight = 44;
            this.m_Button5.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_Button5.SymbolName = "path29851";
            this.m_Button5.SymbolWidth = 38;
            this.m_Button5.TextHeight = 11;
            this.m_Button5.TextValue = 0D;
            this.m_Button5.TextWidth = 50;
            this.m_Button5.Top = 136;
            this.m_Button5.Value = 0D;
            this.m_Button5.VisibleDynamicsValue = true;
            this.m_Button5.VisualPropertiesHashCode = 2129827492;
            this.m_Button5.Width = 56;
            // 
            // m_Text3
            // 
            this.m_Text3.AutoSize = false;
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontSizePixels = 18;
            this.m_Text3.Height = 31;
            this.m_Text3.Left = 95;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.ScreenOwnerName = "QuickFillSetting";
            this.m_Text3.Top = 108;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 339;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(480, 272);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "QuickFillSetting";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_QuickFillSetting = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_QuickFillSetting) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_Button21);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric1);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            this.DrawingPrimitives.Add(this.m_Button2);
            this.DrawingPrimitives.Add(this.m_Button3);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric2);
            this.DrawingPrimitives.Add(this.m_Button4);
            this.DrawingPrimitives.Add(this.m_Button5);
            this.DrawingPrimitives.Add(this.m_Text3);
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button21)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
        }
        
        private void QuickFillSetting_Action_Opened(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("QuickFillSetting", "Opened", "Set Analog", "Tags.CurrentScreen", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.CurrentScreen.SetAnalog(29);
        }
        
        private void m_Button21_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button21", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button21", "Click", "Show Screen", "SettingScreen", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.SettingScreen.Show();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        private void m_Button1_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        private void m_Button2_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button2", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        private void m_Button3_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button3", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        private void m_Button4_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        private void m_Button5_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button5", "Click", "Execute Script", "Buzzer", "");
            Neo.ApplicationFramework.Generated.Globals.Buzzer.Buzz();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(QuickFillSetting));
            this.m_Text1.Text = resources.GetText("QuickFillSetting.Text1.Text", "QUICK FILL SETTINGS");
            this.m_Button21.Text = resources.GetText("QuickFillSetting.Button21.Text", "OK");
            this.m_Text.Text = resources.GetText("QuickFillSetting.Text.Text", "Target Pressure Tolerance (% FSR)");
            this.m_Text2.Text = resources.GetText("QuickFillSetting.Text2.Text", "Stabilization Time (mins)");
            this.m_Text3.Text = resources.GetText("QuickFillSetting.Text3.Text", "Standard Deviation Tolerence (% FSR)");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_QuickFillSetting) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.STDTolerence"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric2.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TargetPressHoldTime"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TargetPressTolerance"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric1.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
        }
    }
}
